### ISSUE TITLE
Installed, but no config screen or discover support

### ISSUE THREAD

**Issue by damiano75** [shenxn/ha-dyson#1]
Hi, I have installed your integration in HACS like custome repository, but I don't know how to config my Dyson device

**Comment by shenxn** [comment]
A new release of up-to-date upstream library (libdyson) is needed. I'll do that later today after solving the login problem and then I'll provide some instructions on how to set up this custom integration for testing.

**Comment by curt7000** [comment]
That would be awesome!  Would love to test!  I'm running 5 fans (we have allergies) with a lot of automations, so hopefully I can stress test it for you.

**Comment by shenxn** [comment]
@damiano75 @curt7000 Good news. I've released version 0.1.0 so that you can install in HACS to test. Note that there are actually two integrations `dyson_local` and `dyson_cloud` to communicate with local device and cloud service, respectively. Due to the limitation of HACS, you'll have to install https://github.com/shenxn/ha-dyson-cloud as well.

Currently only 360 Eye vacuum and Pure Cool Link fan are supported since those are the only devices I have. If you have any of other devices, I'll work on those supports first.

There are a lot of breaking changes compare to the official integration so you may need to fix your automation and scripts. I recommend backing up your current settings before doing anything.

To set up, go to __Configuration__ -> __Integrations__  and set up Dyson Cloud first. Then all devices under your account should be shown as discovered in the integrations page. Then you can configure them using host. You can also leave host blank to use discovery.

**Comment by shenxn** [comment]
If you don't want to use cloud service, you can also set up Dyson Local directly using serial and credential. Then you don't even need the Dyson Cloud integration. To retrieve credentials, check `get_devices.py` in https://github.com/shenxn/libdyson.

**Comment by DarKOrange75** [comment]
@shenxn that is awesome, thank you so much, I've had so much issues with the official integration and its need to log into Dyson account!

**Comment by DarKOrange75** [comment]
> A new release of up-to-date upstream library (libdyson) is needed. I'll do that later today after solving the login problem and then I'll provide some instructions on how to set up this custom integration for testing.

How do you install this library?

**Comment by shenxn** [comment]
@DarKOrange75 To install, you can use HACS by adding https://github.com/shenxn/ha-dyson and https://github.com/shenxn/ha-dyson as custom repositories and install both Dyson Local and Dyson Cloud. Also, you can do this manually by download or clone the repositories and copy the folders `dyson_local` and `dyson_cloud` under `YOUR_CONFIGURATION_FOLDER/custom_integrations/`.

**Comment by DarKOrange75** [comment]
Done and it works like a charm, I wanted to get rid of this connection with Dyson cloud so I configured it to run locally, that is an an awesome job @shenxn, thank you so much! Just a little glitch, temperature and humidity show as 'off'...

**Comment by shenxn** [comment]
@DarKOrange75 The devices only start reporting humidity and temperature a little while after turned on if you don't have continuous monitoring. Ping me if it does not update after a long time and you can see those values in Dyson mobile app.

**Comment by shenxn** [comment]
BTW, do you think it is better to report them as `--` instead of `off` to make it the same as the mobile app do?

**Comment by DarKOrange75** [comment]
IMO I think that off is more intuitive since they are reported only when the fan in 'on', no?

**Comment by shenxn** [comment]
Yes. Then I'll just keep using `off`.

**Comment by DarKOrange75** [comment]
@shenxn, I was trying to update my automations in Node Red but for some reasons fan.pure_cool_link_tower does not show up in the 'call service' block

**Comment by shenxn** [comment]
> @shenxn, I was trying to update my automations in Node Red but for some reasons fan.pure_cool_link_tower does not show up in the 'call service' block (neither in the service tab of the dev tools in HA)

What service are you trying to call?

**Comment by googanhiem** [comment]
This is some really impressive work! Thanks for this great start.

I can't get it working. It appears in my discovery, but when I try to add a host or leave it blank it errors. 

Log says there's an issue with config_flow.py
`AttributeError: 'NoneType' object has no attribute 'serial'`

**Comment by shenxn** [comment]
> This is some really impressive work! Thanks for this great start.
> 
> I can't get it working. It appears in my discovery, but when I try to add a host or leave it blank it errors. 
> 
> Log says there's an issue with config_flow.py
> `AttributeError: 'NoneType' object has no attribute 'serial'`

It seems your device is not supported yet. What is your device model? I'll try to work on that first.

**Comment by googanhiem** [comment]
Mine are the Pure Cool Desk and Pure Cool Tower (the newest models). I just realised they're different than the Pure Cool Link series you mentioned above.

**Comment by curt7000** [comment]
I'm running the Pure Cool Tower TP02 and the   Hot/Cold HP02 fans.

**Comment by DarKOrange75** [comment]
> > @shenxn, I was trying to update my automations in Node Red but for some reasons fan.pure_cool_link_tower does not show up in the 'call service' block (neither in the service tab of the dev tools in HA)
> 
> What service are you trying to call?

With the previous integration I had a service called fan.dyson that I could call to turn on/off the fan. With this one there is no service available or it is in a different domain than "fan"?

**Comment by DarKOrange75** [comment]
OK, that was an issue with Node Red.

Now how do you set speed (from 1 to 10)? Doesn't seem to work like the official integration.

**Comment by shenxn** [comment]
Use `dyson.set_speed`. Currently there are some changes going on in the official fan speed service to make it work better with, e.g. Alexa and HomeKit. See home-assistant/core#45331 and home-assistant/core#45407. `dyson.set_speed` is only a temporary solution and I'll switch to percentage when that is release in core.

**Comment by DarKOrange75** [comment]
> Use `dyson.set_speed`. Currently there are some changes going on in the official fan speed service to make it work better with, e.g. Alexa and HomeKit. See [home-assistant/core#45331](https://github.com/home-assistant/core/pull/45331) and [home-assistant/core#45407](https://github.com/home-assistant/core/pull/45407). `dyson.set_speed` is only a temporary solution and I'll switch to percentage when that is release in core.

Great, thank you for your fast answer.

**Comment by DarKOrange75** [comment]
@shenxn sorry to bother you again, I promise it's the last time ;-) In order to call dyson_local.set_speed in Node Red I need to specify a 'Domain' can't find a proper one for this service any idea?
<img width="858" alt="Capture d’écran 2021-02-12 à 15 57 04" src="https://user-images.githubusercontent.com/40524270/107783898-10fe2d00-6d4b-11eb-8ad7-3b19a5039c99.png">

**Comment by shenxn** [comment]
I think domain should be set to `dyson_local` and service should be `set_speed`.

**Comment by DarKOrange75** [comment]
@shenxn  I figured it out after I posted, sorry for my dumb question! 
I am all set, everything is now working like previously with the official integration except that now it doesn't rely on Dyson's Cloud availability and changes! Thank you so much!

**Comment by msvinth** [comment]
Hi @shenxn 
Great work here. Really looking forward to have a local only integration.
For now I also get
AttributeError: 'NoneType' object has no attribute 'serial'
error as mentioned above.

I have the Dyson Pure Cool Tower TP04.

**Comment by jason0x43** [comment]
I'm also very excited about this, particularly the local control option. I haven't tried to install it yet, but I have an HP04 Pure Hot+Cool, which I don't think is supported yet (just adding it to the support queue 😁).

**Comment by curt7000** [comment]
@shenxn I installed via the Cloud option and its working great for my TP02 Tower.  Awesome work!  Will patiently wait for support for the HP02.

**Comment by shenxn** [comment]
@googanhiem @msvinth I've released version 0.2.0 which supports Dyson Pure Cool, Dyson Pure Cool Desk, and Dyson Pure Cool Humidity. Remember to update both `dyson_local` and `dyson_cloud` to avoid upstream library version conflict if you have both installed. Since I don't have those devices so it may not work.

Also, notice that there is a unique ID change for switches so you may see duplicated switches for existed devices. Feel free to remove the unavailable one or you can remove and re-add.

**Comment by msvinth** [comment]
> @googanhiem @msvinth I've released version 0.2.0 which supports Dyson Pure Cool, Dyson Pure Cool Desk, and Dyson Pure Cool Humidity. Remember to update both `dyson_local` and `dyson_cloud` to avoid upstream library version conflict if you have both installed. Since I don't have those devices so it may not work.

That was quick @shenxn. Can now confirm that Dyson Pure Cool Tower TP04 works!
Thanks a lot.

**Comment by googanhiem** [comment]
It’s working great for desk and tower! Thanks @shenxn 
Really feels like the future of this integration.

**Comment by damiano75** [comment]
Hi, my Dyson is an HP02, the integration discovered it but when I put the local IP in Host field I have this message:

![image](https://user-images.githubusercontent.com/47896789/107933316-e3012e80-6f7e-11eb-9a59-f12f50341a89.png)

is it because it is not supported yet?

**Comment by shenxn** [comment]
> Hi, my Dyson is an HP02, the integration discovered it but when I put the local IP in Host field I have this message:
> 
> ![image](https://user-images.githubusercontent.com/47896789/107933316-e3012e80-6f7e-11eb-9a59-f12f50341a89.png)
> 
> is it because it is not supported yet?

Yes, it is not supported yet and caused that error.

**Comment by shenxn** [comment]
@curt7000 @jason0x43 @damiano75 Version 0.3.0 is released. HP devices (Pure Hot+Cool and Pure Hot+Cool link) are now supported.

**Comment by arnerek** [comment]
Great work with this library/integration! i have an HP04 and had to include DEVICE_PURE_HOT_COOL in https://github.com/shenxn/libdyson/blob/9fd6521affb8b08cc7fea5fb787cae9b93665422/libdyson/const.py#L13. Then it worked perfectly! 👍

**Comment by Ulrar** [comment]
Hey,

Just used this with the get_devices.py script to set it up without the cloud integration, works like a charm !
Might be good to put that in the readme, since this integration is the only one working right now I expect a lot of people will be coming here in the next few weeks looking for a way to set this up.

Thanks for your work !

**Comment by damiano75** [comment]
Ok, it really works great, do you think you will add support to set auto mode and speed (1-10), like the dyson.set_speed and dyson.set_auto_mode services? Please, continue to develop this integration: with the official one every time I unplug the HP02 HA loses the connection and I need to restart HA.

Many many thanks

**Comment by shenxn** [comment]
@damiano75 Those are actually already supported. Use `dyson_local.set_speed` and `dyson_local.set_auto_mode`.

**Comment by damiano75** [comment]
@shenxn I finally migrated all my scripts to dyson local: great work! I hope your integration will be the official one.
Thank you again for your work

**Comment by ebarretopr** [comment]
> @DarKOrange75 To install, you can use HACS by adding https://github.com/shenxn/ha-dyson and https://github.com/shenxn/ha-dyson as custom repositories and install both Dyson Local and Dyson Cloud. Also, you can do this manually by download or clone the repositories and copy the folders `custom_integrations/dyson_local` and `custom_integrations/dyson_cloud` to under `YOUR_CONFIGURATION_FOLDER/custom_integrations/`.

Did this but nothings appears no config options or discovery for me. Apologize before hand, i'm basic on HA

**Comment by tsmanz** [comment]
> > @DarKOrange75 To install, you can use HACS by adding https://github.com/shenxn/ha-dyson and https://github.com/shenxn/ha-dyson as custom repositories and install both Dyson Local and Dyson Cloud. Also, you can do this manually by download or clone the repositories and copy the folders `custom_integrations/dyson_local` and `custom_integrations/dyson_cloud` to under `YOUR_CONFIGURATION_FOLDER/custom_integrations/`.
> 
> Did this but nothings appears no config options or discovery for me. Apologize before hand, i'm basic on HA

I'm also not seeing anything in Configuration - Integrations after installing both Dyson Local and Dyson Cloud via HACS and rebooting. Am on Home Assistant 2021.3.0, rpi4-64 if that helps.

**Comment by lolongan** [comment]
> Great work with this library/integration! i have an HP04 and had to include DEVICE_TYPE_PURE_HOT_COOL in https://github.com/shenxn/libdyson/blob/9fd6521affb8b08cc7fea5fb787cae9b93665422/libdyson/const.py#L13. Then it worked perfectly! 👍

I install shenxn/ha-dyson using HACS and then, when trying to set-up the Dyson_Local integration, in the dropdown list "Device Type", I can see "360 eyes ...", "Pure Cool Link", "Pure Humidity + Cool", etc. but no "Pure Hot + Cool".
Do you know how to make this last choice appear or how to enter it ?

**Comment by lolongan** [comment]
> > > @DarKOrange75 To install, you can use HACS by adding https://github.com/shenxn/ha-dyson and https://github.com/shenxn/ha-dyson as custom repositories and install both Dyson Local and Dyson Cloud. Also, you can do this manually by download or clone the repositories and copy the folders `custom_integrations/dyson_local` and `custom_integrations/dyson_cloud` to under `YOUR_CONFIGURATION_FOLDER/custom_integrations/`.
> > 
> > 
> > Did this but nothings appears no config options or discovery for me. Apologize before hand, i'm basic on HA
> 
> I'm also not seeing anything in Configuration - Integrations after installing both Dyson Local and Dyson Cloud via HACS and rebooting. Am on Home Assistant 2021.3.0, rpi4-64 if that helps.

You need to click on <+ Add Integration>

**Comment by tsmanz** [comment]
> > > > @DarKOrange75 To install, you can use HACS by adding https://github.com/shenxn/ha-dyson and https://github.com/shenxn/ha-dyson as custom repositories and install both Dyson Local and Dyson Cloud. Also, you can do this manually by download or clone the repositories and copy the folders `custom_integrations/dyson_local` and `custom_integrations/dyson_cloud` to under `YOUR_CONFIGURATION_FOLDER/custom_integrations/`.
> > > 
> > > 
> > > Did this but nothings appears no config options or discovery for me. Apologize before hand, i'm basic on HA
> > 
> > 
> > I'm also not seeing anything in Configuration - Integrations after installing both Dyson Local and Dyson Cloud via HACS and rebooting. Am on Home Assistant 2021.3.0, rpi4-64 if that helps.
> 
> You need to click on <+ Add Integration>

I'm familiar with how HA integrations work so I did press the Add button but there was no Dyson Cloud or Dyson Local integrations available initially until I did the following...

Once both Dyson Cloud and Dyson Local Integrations are installed via HACS. Make sure the Dyson Link app on your phone is the latest version then log out of the Dyson Link app and log back in using the 2FA code that is emailed to you. As soon as you're logged into the Dyson Link app, restart HA. Once HA has restarted, Dyson Cloud and Dyson Local integrations should appear when you press the Add button  in Configuration > Integrations. I then used the Dyson Cloud integration to get the initial connection using my Dyson Link app credentials, then used the Dyson Local integration to add my fan to HA.

The above worked for me the make Dyson Local and Dyson Cloud appear when adding Integrations so I could then set them up. Not sure if it was due to the Dyson Link app needing an update so 2FA was required to log in but it's all working now. Thanks very much to all the devs spending time on this!

**Comment by ebarretopr** [comment]
> > > > > @DarKOrange75 To install, you can use HACS by adding https://github.com/shenxn/ha-dyson and https://github.com/shenxn/ha-dyson as custom repositories and install both Dyson Local and Dyson Cloud. Also, you can do this manually by download or clone the repositories and copy the folders `custom_integrations/dyson_local` and `custom_integrations/dyson_cloud` to under `YOUR_CONFIGURATION_FOLDER/custom_integrations/`.
> > > > 
> > > > 
> > > > Did this but nothings appears no config options or discovery for me. Apologize before hand, i'm basic on HA
> > > 
> > > 
> > > I'm also not seeing anything in Configuration - Integrations after installing both Dyson Local and Dyson Cloud via HACS and rebooting. Am on Home Assistant 2021.3.0, rpi4-64 if that helps.
> > 
> > 
> > You need to click on <+ Add Integration>
> 
> I'm familiar with how HA integrations work so I did press the Add button but there was no Dyson Cloud or Dyson Local integrations available initially until I did the following...
> 
> Once both Dyson Cloud and Dyson Local Integrations are installed via HACS. Make sure the Dyson Link app on your phone is the latest version then log out of the Dyson Link app and log back in using the 2FA code that is emailed to you. As soon as you're logged into the Dyson Link app, restart HA. Once HA has restarted, Dyson Cloud and Dyson Local integrations should appear when you press the Add button in Configuration > Integrations. I then used the Dyson Cloud integration to get the initial connection using my Dyson Link app credentials, then used the Dyson Local integration to add my fan to HA.
> 
> The above worked for me the make Dyson Local and Dyson Cloud appear when adding Integrations so I could then set them up. Not sure if it was due to the Dyson Link app needing an update so 2FA was required to log in but it's all working now. Thanks very much to all the devs spending time on this!

The actions performed at the end worked for me

**Comment by lolongan** [comment]
> > > > > > @DarKOrange75 To install, you can use HACS by adding https://github.com/shenxn/ha-dyson and https://github.com/shenxn/ha-dyson as custom repositories and install both Dyson Local and Dyson Cloud. Also, you can do this manually by download or clone the repositories and copy the folders `custom_integrations/dyson_local` and `custom_integrations/dyson_cloud` to under `YOUR_CONFIGURATION_FOLDER/custom_integrations/`.
> > > > > 
> > > > > 
> > > > > Did this but nothings appears no config options or discovery for me. Apologize before hand, i'm basic on HA
> > > > 
> > > > 
> > > > I'm also not seeing anything in Configuration - Integrations after installing both Dyson Local and Dyson Cloud via HACS and rebooting. Am on Home Assistant 2021.3.0, rpi4-64 if that helps.
> > > 
> > > 
> > > You need to click on <+ Add Integration>
> > 
> > 
> > I'm familiar with how HA integrations work so I did press the Add button but there was no Dyson Cloud or Dyson Local integrations available initially until I did the following...
> > Once both Dyson Cloud and Dyson Local Integrations are installed via HACS. Make sure the Dyson Link app on your phone is the latest version then log out of the Dyson Link app and log back in using the 2FA code that is emailed to you. As soon as you're logged into the Dyson Link app, restart HA. Once HA has restarted, Dyson Cloud and Dyson Local integrations should appear when you press the Add button in Configuration > Integrations. I then used the Dyson Cloud integration to get the initial connection using my Dyson Link app credentials, then used the Dyson Local integration to add my fan to HA.
> > The above worked for me the make Dyson Local and Dyson Cloud appear when adding Integrations so I could then set them up. Not sure if it was due to the Dyson Link app needing an update so 2FA was required to log in but it's all working now. Thanks very much to all the devs spending time on this!
> 
> The actions performed at the end worked for me

This does not work if the Dyson Link app does not access internet from the same IP address as HA.

**Comment by eiddor** [comment]
> This does not work if the Dyson Link app does not access internet from the same IP address as HA.

This was _exactly_ my problem with the workaround.

My HA is on the same server as Plex, which I have going out a different Internet provider so that my kids don't kill my bandwidth when they stream.  Thanks for the reminder!

Native isn't working, but Dyson Cloud works, and I was able to get credentials so I can use Dyson Local.

**Comment by shenxn** [comment]
2FA is now supported. Now you should be able to login through Dyson Cloud.

**Comment by lolongan** [comment]
> 2FA is now supported. Now you should be able to login through Dyson Cloud.

It does work perfectly. Thanks a lot, @shenxn 
Only thing is that, for me, after setting up Dyson_Cloud, Dyson_Local still ask for Serial, Credential and Device Types.
(it's not an issue for me, I've been able to set up Dyson_Local, just want to let you know).

**Comment by shenxn** [comment]
> > 2FA is now supported. Now you should be able to login through Dyson Cloud.
> 
> It does work perfectly. Thanks a lot, @shenxn
> Only thing is that, for me, after setting up Dyson_Cloud, Dyson_Local still ask for Serial, Credential and Device Types.
> (it's not an issue for me, I've been able to set up Dyson_Local, just want to let you know).

After setting up Dyson Cloud, you should be able to see discovered entries and you can set up Dyson Local directly through those entries. If you choose to set up manually (from the + menu) then yes you still need to type in all the information.

**Comment by lolongan** [comment]
> 
> After setting up Dyson Cloud, you should be able to see discovered entries and you can set up Dyson Local directly through those entries. If you choose to set up manually (from the + menu) then yes you still need to type in all the information.

Then, sorry for newbies question, but where should I see those discovered entries ? 
Indeed I setup Dyson Cloud but can not find anything so I had to setup Dyson Local from the + menu.
Below is what I have, inn the Dyson Cloud box, it shows only my email ID
<img width="618" alt="Capture d’écran 2021-03-07 à 11 13 02" src="https://user-images.githubusercontent.com/76393476/110236580-d5641680-7f36-11eb-8c4e-a3363f293e66.png">

**Comment by shenxn** [comment]
@lolongan You should see something like this. Note that if your device is already set up, the discovered entity will not be shown. If you have some time, you can try remove your Dyson Local entry, reload Dyson Cloud or restart your HA, then see if there is any discovered entity. If not, see if there is anything related in your log.
![Screenshot from 2021-03-07 18-36-36](https://user-images.githubusercontent.com/7052824/110237062-b1272a80-7f74-11eb-81ae-1bd88b583dd1.png)

**Comment by lolongan** [comment]
> @lolongan You should see something like this. Note that if your device is already set up, the discovered entity will not be shown. If you have some time, you can try remove your Dyson Local entry, reload Dyson Cloud or restart your HA, then see if there is any discovered entity. If not, see if there is anything related in your log.
> ![Screenshot from 2021-03-07 18-36-36](https://user-images.githubusercontent.com/7052824/110237062-b1272a80-7f74-11eb-81ae-1bd88b583dd1.png)

@shenxn Thanks for pointing this out. I have never seen these entries, since the very first time I tried to install Dyson_Cloud a few weeks ago (and succeeded). Maybe I have some issue with Discovery I'll need to find out (although I have put `discovery:` in my configuration.yaml).
One more question: if I had 2 or more Dyson devices, is it possible (and how) to install them only with Dyson_Local ? Or should I go through Dyson_Cloud for it to discover the additional devices ?

**Comment by shenxn** [comment]
@lolongan If there is no discovered entries, there is something gone wrong. It has nothing to do with the built in `discovery` integration.

To set up multiple devices, the easiest way is through Dyson Cloud and discovered entries. You can also set up Dyson Local manually. See https://github.com/shenxn/ha-dyson#setup for more information.

**Comment by lolongan** [comment]
> @lolongan If there is no discovered entries, there is something gone wrong. It has nothing to do with the built in `discovery` integration.
> 
> To set up multiple devices, the easiest way is through Dyson Cloud and discovered entries. You can also set up Dyson Local manually. See https://github.com/shenxn/ha-dyson#setup for more information.

Yes, indeed there is an error in Dyson_Cloud:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/dyson_cloud/__init__.py", line 43, in async_setup_entry
    devices = await hass.async_add_executor_job(account.devices)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/libdyson/cloud/account.py", line 173, in devices
    devices.append(DysonDeviceInfo.from_raw(raw))
  File "/usr/local/lib/python3.8/site-packages/libdyson/cloud/device_info.py", line 31, in from_raw
    decrypt_password(raw["LocalCredentials"]),
  File "/usr/local/lib/python3.8/site-packages/libdyson/cloud/utils.py", line 29, in decrypt_password
    encrypted = base64.b64decode(encrypted_password)
  File "/usr/local/lib/python3.8/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/local/lib/python3.8/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```

**Comment by gfawkes66** [comment]
I have tried the steps outlined above - update app, login to app with 2FA code, install 2 HACS integrations and reboot.
But unfortunately, when i go to configuration/integrations there is no dyson cloud or dyson local to add when i hit +.
not sure if im missing something.
I would post some logs but am not sure where to look.
This integration does look really promising though.
Thanks.

**Comment by lolongan** [comment]
> I have tried the steps outlined above - update app, login to app with 2FA code, install 2 HACS integrations and reboot.
> But unfortunately, when i go to configuration/integrations there is no dyson cloud or dyson local to add when i hit +.
> not sure if im missing something.
> I would post some logs but am not sure where to look.
> This integration does look really promising though.
> Thanks.

Do you see these integrations shown in the HACS/Integrations screen ?
If yes, then you should find these integrations when hitting + in the Configuration/Integrations screen, as shown below.
If not, then look at Configuration/Logs to see if there is any issue/error.
<img width="526" alt="Capture d’écran 2021-03-07 à 13 30 12" src="https://user-images.githubusercontent.com/76393476/110239926-cf2b6580-7f49-11eb-9a76-538699221262.png">

**Comment by gfawkes66** [comment]
Hi, thanks for the reply - to clarify -

This is all that appears in the log .
You are using a custom integration dyson_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
You are using a custom integration dyson_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

but despite that nothing in integrations (i have updated the Dyson app, logged out and in and restarted Home assistant 2021.3.2):-
![image](https://user-images.githubusercontent.com/13612122/110241391-68597c80-7f48-11eb-86f3-8cb2225b2378.png)

**Comment by iceman23e** [comment]
@gfawkes66 Have you tried clearing your browser cache or using incognito/private?

**Comment by gfawkes66** [comment]
> 
> 
> @gfawkes66 Have you tried clearing your browser cache or using incognito/private?

Thanks very much. icognito / private was indeed the issue. Hopefully this will help someone else.
I have successfully setup Dyson Local.

**Comment by shenxn** [comment]
@lolongan This seems to be a problem in the upstream library `libdyson`. I've created a new issue (shenxn/libdyson#2) there to track this problem.

**Comment by shenxn** [comment]
This issue is growing very long and hard to track. I'm closing this since the original problem has been solved. If anyone has any other problem, feel free to create a new issue.
