### ISSUE TITLE
Feature: compatibility with the new percentages

### ISSUE THREAD

**Issue by lenwar** [shenxn/ha-dyson#10]
Hi,

Since HA 2021.3, HA uses percentages in favour of the 'low-medium-high' system.

It would be nice if ha-dyson would link 10% to 1, 20% to 2, etc, in favour of low to 4, etc.

**Comment by shenxn** [comment]
That is actually already supported in another branch. I'll merge that into main.

**Comment by shenxn** [comment]
Version 0.5.0 supports that. See [release note](https://github.com/shenxn/ha-dyson/releases/tag/v0.5.0) for more information.

**Comment by shenxn** [comment]
I'm on a business trip so currently I don't have access to any Dyson device. I'm not 100% sure it works. Please ping me if anything not working as expected.

**Comment by lenwar** [comment]
Hi,
Thanks for your quick response!!
It works just fine now 😊

**Comment by DarKOrange75** [comment]
Hi @shenxn,

Sorry for my dumb question but the new percentage feature broke my node-red automation and I can't fix it, I get an extra key  not allowed message. Any idea on how to fix this?

Thank you very much :-)

<img width="1029" alt="Capture d’écran 2021-03-09 à 20 08 53" src="https://user-images.githubusercontent.com/40524270/110524494-c4243100-8113-11eb-891a-0f2f8a8e4e56.png">
