### ISSUE TITLE
Dyson Purifier Cool Formaldehyde

### ISSUE THREAD

**Issue by enricozocca** [shenxn/ha-dyson#102]
I own a "Dyson Purifier Cool Formaldehyde". I have currently configured the Local integration by selecting the "Pure Cool Formaldehyde" model. Everything works but some information is missing such as the AIQ index. It's correct? I tried to use other models but it doesn't work.
Thank you
Enrico

**Comment by Kakise** [comment]
AIQ is not a supported sensor in ha-dyson, this is intended and won't be fixed. You can calculate AQI by making your own macro and add it to the dashboard.
