### ISSUE TITLE
Pure Humidify+Cool 358 AIQ missing

### ISSUE THREAD

**Issue by wuast94** [shenxn/ha-dyson#107]
All working fine but the AIQ (Air Quality Index) is missing, if i can help let me know. 

Used this integration (or the cloud one) some time ago and i know that i had this readings, with the local one its gone 🙂

**Comment by Kakise** [comment]
Sorry but now we rely on the reading of the different sensor (PM2.5, PM10 and VOC) as that just makes more sense. 

You can calculate the AQI pretty easily with tools like https://www.airnow.gov/aqi/aqi-calculator-concentration/ or even make your own dashboard widget.
