### ISSUE TITLE
More service options.

### ISSUE THREAD

**Issue by charis0728** [shenxn/ha-dyson#11]
This is an amazing custom component and very good substitute for original built-in dyson integration.
But I cannot find the services for night mode and flow direction.
Is there any way to control these features?

**Comment by shenxn** [comment]
This integration uses switches instead of custom services to turn on/off night mode and flow direction. I'll add that into README.

**Comment by charis0728** [comment]
@shenxn Thank you for your reply. I found the switches. I didn't even think about switches for those services.

**Comment by shenxn** [comment]
Additional services added in version 0.5.2
