### ISSUE TITLE
Ip used for connection to dyson

### ISSUE THREAD

**Issue by CharlPels** [shenxn/ha-dyson#110]
More a request then an issue i guess

last day my router stopt working, the new one offcource gives all devices a new ip in same range however I don’t know the IP address of one of my dysons :(.
The one i did now is working again.
If there way way to find the IP address that is used by dyson-local so I can set the dyson back to org IP and hopefully all works again.

dyson-cloud, is not working i guess, kan login and get success en from there it fails.

**Comment by Kakise** [comment]
All devices ip in hassio should be stored here: `~/.homeassistant/.storage/core.device_registry`

As for ips in your router you should have a list of connected devices to your router inside your router's lan configuration

**Comment by CharlPels** [comment]
Thanks, the issue is that my router stopped working and I have a new one and so the is no dhcp config to copy the config from? How is the relationship between dyson and HA? One dyson I had the old ip and that one is working fine again, the second I don’t have the ip anymore. However, serial, mac etc of the dyson is still the same and on the same wifi with the same wifi id etc etc, so what is preventing it from working again. HA is offcource also the same with the same config.
