### ISSUE TITLE
Cannot connect to Dyson cloud service

### ISSUE THREAD

**Issue by aberkeley** [shenxn/ha-dyson#111]
Hi
i have tried logging in an out of the app several times and i still get this in my logs:

Cannot connect to Dyson cloud service.

this is on latest HA running as supervisor on RPI3. Even with debug logs on - this all the info i get

**Comment by Kakise** [comment]
The problem should have been fixed in v0.16.4-3 according to my testing. Don't forget to logout of the app before attempting to connecting and use get_devices.py script in shenxn/libdyson if you still have troubles
