### ISSUE TITLE
Can't delete or update.

### ISSUE THREAD

**Issue by monsieurlatte** [shenxn/ha-dyson#116]
When I try to delete the integration in HA 2022.4 I get this.

ImportError: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)

If I try to set it up I get this for both.

Setup failed for custom integration dyson_cloud: Unable to import component: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)

**Comment by Flameeyes** [comment]
This is because there's two different required versions for dyson_local and dyson_cloud — remove dyson_cloud and it should force an update to a compatible libdyson for dyson_local.

**Comment by townsmcp** [comment]
I don’t have Dyson Cloud installed so don’t think that is the problem

**Comment by Flameeyes** [comment]
Hmm, that's interesting then — it sounds like it's not updating libdyson from the git version (that's what the error means: it's using a too-old version of libdyson.)

**Comment by monsieurlatte** [comment]
Hmm I finally deleted everything, in HACS and HA.  THen added dyson local only via HACS (16.3) and in HA when I go to run it it says this can't be run from the UI.

**Comment by Flameeyes** [comment]
(Discussion is on #115, with solution.)

**Comment by monsieurlatte** [comment]
The pip commands work great, only issue is it changed some of my stuff, I lost the auto switch (fixed by just changing my code for my controls for it).

**Comment by Anto79-ops** [comment]
@monsieurlatte could you please tell me where you typed those pip commands? Did you just type them into the terminal in HAOS? I tried that last night and it got some meessage like uninstallted slopped because libdyson is not installed and then when I tried the second pip command, it was stuck tring to install some dependcies and kepy looping (with lots of red lines of text) and then eventually I just ctrl + C is stopped the process. If you could shed some light how you ran those pip lines in HAOS (with HACS), that would be awesome!

**Comment by monsieurlatte** [comment]
I used the add on called portainer, then connected to home assistant through that, the HAOS terminal is not the same thing.

**Comment by Anto79-ops** [comment]
@monsieurlatte thank you for this information. Just looked into Portainer add-on and comes with lots of warning thus it seems a bit to hackey for me....ok, guess I'll wait for something easier or perhaps the awesome developers will issue an update/fix soon.

**Comment by Kakise** [comment]
> The pip commands work great, only issue is it changed some of my stuff, I lost the auto switch (fixed by just changing my code for my controls for it).

The auto switch disappearing is intended, it was replaced by the fan service a few updates ago


> @monsieurlatte thank you for this information. Just looked into Portainer add-on and comes with lots of warning thus it seems a bit too hackey for me....ok, guess I'll wait for something easier or perhaps the awesome developers will issue an update/fix soon.

0.16.4 should fix these problems
