### ISSUE TITLE
Temp no longer available after update to 2022.4

### ISSUE THREAD

**Issue by EDelsman** [shenxn/ha-dyson#118]
Since the update to 2022.4 the temperature sensor is no longer available for the dyson pure humidify and cool. Other entities work as expected.

**Comment by Flameeyes** [comment]
That's fixed on 0.16.3 (but the other entities are still broken, see #117.)

**Comment by Kakise** [comment]
All fixed in v0.16.4 thanks to @Flameeyes

**Comment by EDelsman** [comment]
Works great again - Thanks!
