### ISSUE TITLE
New update showing long temperature read

### ISSUE THREAD

**Issue by heyepic** [shenxn/ha-dyson#120]
Did the latest update via HACS.

Temperature sensor on one of my Dyson's fans is reading as: 70.9700000000001 °F

**Comment by Kakise** [comment]
I can't reproduce, can you confirm that it persists in v0.16.4 ?

**Comment by heyepic** [comment]
Issue seems to have gone away!

**Comment by kwbeck** [comment]
Same thing here.  Was originally showing 10+ places to the right of the decimal, but after reloading the integration, it is now just showing 2 places.

**Comment by cheeplusplus** [comment]
This is happening for me now too, on 0.16.4-4

**Comment by heyepic** [comment]
Bummer. Still fine on my end, but noticed too, that after awhile the integration just fails and I have to manually reload. The error I'm receiving is 'Failed to call service fan/set_percentage' when attempting to adjust. I then went into the entity and it's just fully unresponsive. I did not have any of these issues until the latest update.

**Comment by kwbeck** [comment]
It's started happening again for me too....
