### ISSUE TITLE
Error setting up

### ISSUE THREAD

**Issue by ad2022uk** [shenxn/ha-dyson#128]
Error setting up with error presented

Running latest HA build as VM on Synology.

![Screenshot_20220414-211143_Home Assistant](https://user-images.githubusercontent.com/101991409/163468221-b2ba1a32-d676-44a8-9431-7ffae602beff.png)

**Comment by BeardyBrah** [comment]
same thing here
Running on Generic x86-64 build. 

![image](https://user-images.githubusercontent.com/66730427/163502650-b344c3a1-ebb6-42d7-90d4-ae9c63c80733.png)

**Comment by ad2022uk** [comment]
So I removed my old instances and deleted both Dyson local and cloud in HACS, reinstalled it and randomly started to work again. I had to do that a few times before that error disappeared (maybe like 4 times installing and removing with restarts in-between each step).

No idea why, but it worked.
I've set it up locally now.

**Comment by dantz** [comment]
same issue here

**Comment by holger81** [comment]
The problem for me was that Dyson cloud requires a libdyson=0.8.7 in the manifest.json file (in config/custom_components/dyson_cloud). After changing this to 0.8.11, everything worked fine.

**Comment by Kakise** [comment]
Dyson cloud is not maintained anymore. Please do not use it.
