### ISSUE TITLE
v0.5.1 : Error messages and no 'fan.xxxx' entity in Dyson Local integration

### ISSUE THREAD

**Issue by charis0728** [shenxn/ha-dyson#13]
**After I upgraded this component to v0.5.1., I got an error message like this.**

Invalid config
The following integrations and platforms could not be set up:

dyson_local.fan
Please check your config and logs.

**And error logs:**

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172 
First occurred: 오전 12:37:52 (5 occurrences) 
Last logged: 오전 12:38:00

Error unloading entry 서재 for fan
Error unloading entry 서재 for air_quality
Error unloading entry 서재 for sensor
Error unloading entry 서재 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 325, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 105, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

Logger: homeassistant.setup
Source: setup.py:280 
First occurred: 오전 12:35:17 (2 occurrences) 
Last logged: 오전 12:39:09

Unable to prepare setup for platform dyson_local.fan: Platform not found (No module named 'homeassistant.util.percentage').

**There was no error messages like this in previous version.
And 'fan.xxxx' entity is not created.
Other entities(sensors and switches) are created and works well.**

**Comment by shenxn** [comment]
What is the version of your Home Assistant? You'll need at least 2021.3.0 to run version 5.0+

**Comment by charis0728** [comment]
Thank you for your reply.
That's a bad news, because I'm running 2021.2.3.
I cannot upgrade to 2021.3.2 yet, because a custom component I use conflict with new version.
After I upgrade to newer version, I'll try again.

**Comment by charis0728** [comment]
Can you make a minor upgrade version of v.0.4.0?(correcting the problem 'off' status when dyson fan is idle) 
Or can you show me how I can modify v0.4.0 component files?
I'm so sorry to bother you.

**Comment by shenxn** [comment]
Sorry but that is currently not possible since it is actually a change in the upstream library `libdyson`. However, if you upgrade `libdyson`, it is going to break other parts of the integration. Sorry for the inconvenience. I'll think about it and will let you know if I have a work around.
