### ISSUE TITLE
How to: Setup using device WiFi information

### ISSUE THREAD

**Issue by sjuratov** [shenxn/ha-dyson#131]
Sorry for noob question. I have installed Home Assistant 2022.4.6 in a container on Synology NAS. I was able to install HACS and add _Dyson Local_. So if I go to HACS->Integrations, I see _HACS_ and _Dyson Local_.

I am at the point where I want to setup my Dyson Pure Cool Link using device WiFi information. I have device SSID and password (sticker) and if I understand setup correctly, I should now _Set up through UI and select "Setup using WiFi information"._ 

My problem is that I can't figure out where in HA I should find this UI. I've looked everywhere but just can't find it.

Any guidance is appreciated.

**Comment by Kakise** [comment]
> Sorry for noob question. I have installed Home Assistant 2022.4.6 in a container on Synology NAS. I was able to install HACS and add _Dyson Local_. So if I go to HACS->Integrations, I see _HACS_ and _Dyson Local_.
> 
> I am at the point where I want to setup my Dyson Pure Cool Link using device WiFi information. I have device SSID and password (sticker) and if I understand setup correctly, I should now _Set up through UI and select "Setup using WiFi information"._
> 
> My problem is that I can't figure out where in HA I should find this UI. I've looked everywhere but just can't find it.
> 
> Any guidance is appreciated.

The relevant pop-up will pop when you add the "Dyson local" integration in the integrations settings

**Comment by sjuratov** [comment]
Thanks @Kakise. I have just tried following.

1. HACS->Integration->Dyson Local, then clicked on three dots and _Remove_
2. HACS->Integration, then clicked on three dots in top right, selected custom repositories and removed Dyson Local
3. At this point I assume I am ready to install Dyson Local from scratch
4. HACS->Integration, then clicked on three dots in top right, selected custom repositories and add https://github.com/shenxn/ha-dyson with category Integration
5. HACS->Integration, then click on _Explore & Downloaded Repositories_, search for Dyson Local
6. Click on Dyson Local, repo page opens (inside of HACS) and in bottom right, click on _Download this repository with HACS_
7. Select latest version (v0.16.4-4) and click on Download. _Note: I have also tried with v0.16.4_
8. At this point, Dyson Local is visible in HACS->Integration with _Pending Restart_
9. I restart HA and go back to HACS->Integration. Dyson Local is visible (without _Pending Restart_)
10. At no point I get a pop-up to do WiFi setup

Not sure what am I doing wrong, where to look for some further troubleshooting.

FWIW, here are dyson related log entries:

`2022-04-28 11:24:06 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration dyson_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
...
2022-04-28 11:24:36 DEBUG (MainThread) [custom_components.hacs] <Integration shenxn/ha-dyson> Getting repository information
...
2022-04-28 11:24:37 DEBUG (MainThread) [custom_components.hacs] <Integration shenxn/ha-dyson> Running checks against v0.16.4-4
`

**Comment by coreywillwhat** [comment]
> Thanks @Kakise. I have just tried following.
> 
>     1. HACS->Integration->Dyson Local, then clicked on three dots and _Remove_
> 
>     2. HACS->Integration, then clicked on three dots in top right, selected custom repositories and removed Dyson Local
> 
>     3. At this point I assume I am ready to install Dyson Local from scratch
> 
>     4. HACS->Integration, then clicked on three dots in top right, selected custom repositories and add https://github.com/shenxn/ha-dyson with category Integration
> 
>     5. HACS->Integration, then click on _Explore & Downloaded Repositories_, search for Dyson Local
> 
>     6. Click on Dyson Local, repo page opens (inside of HACS) and in bottom right, click on _Download this repository with HACS_
> 
>     7. Select latest version (v0.16.4-4) and click on Download. _Note: I have also tried with v0.16.4_
> 
>     8. At this point, Dyson Local is visible in HACS->Integration with _Pending Restart_
> 
>     9. I restart HA and go back to HACS->Integration. Dyson Local is visible (without _Pending Restart_)
> 
>     10. At no point I get a pop-up to do WiFi setup
> 
> 
> Not sure what am I doing wrong, where to look for some further troubleshooting.
> 
> FWIW, here are dyson related log entries:
> 
> `2022-04-28 11:24:06 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration dyson_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant ... 2022-04-28 11:24:36 DEBUG (MainThread) [custom_components.hacs] <Integration shenxn/ha-dyson> Getting repository information ... 2022-04-28 11:24:37 DEBUG (MainThread) [custom_components.hacs] <Integration shenxn/ha-dyson> Running checks against v0.16.4-4 `

Once installed through HACS, you'll need to go through the normal integration menu, not HACS, to do the setup.
Configuration > Devices & Services > Integrations > Click the "+ add integration" at the bottom right and search for dyson local there

**Comment by sjuratov** [comment]
Awesome! Many thanks!

**Comment by coreywillwhat** [comment]
> Awesome! Many thanks!

No worries! Just make sure to close this issue if resolved.
