### ISSUE TITLE
Broken in beta branch 2022.5.0b4

### ISSUE THREAD

**Issue by illuzn** [shenxn/ha-dyson#133]
My pure cool fan is showing as unavailable in this version of the beta. I'm not sure what the breaking change that has been introduced is but I can confirm it was working in 2022.5.0b3.

**Comment by Kakise** [comment]
Hello,
I am currently investigating the issue. Can you please give me logs about the integration please ?

**Comment by Anto79-ops** [comment]
just updated to 2022.5...been about 40 minutes and Dyson integration seems to be working normally. Did yours break instantly?

**Comment by illuzn** [comment]
Sorry for the false alarm... looks like it is fixed in the final release of HA 2022.5
