### ISSUE TITLE
Failure to install in Integrations

### ISSUE THREAD

**Issue by andrewtobin** [shenxn/ha-dyson#135]
Hi, I can't sign up to the forums on home assistant, as they're not accepting new accounts, so I hope it's okay to post here.

I have followed the instructions, and I am in Integrations and adding both the cloud and local Dyson as new integrations and I get this message:

> This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

I am running the latest version of HA as of today - Home Assistant Core 2022.5.3

**Comment by Mrmiffo** [comment]
I have the exact same issue when trying to install the cloud version. In the logs it was complaining that component dyson_local was missing. So I added it to hacs as well. Now when I try to add the integration I get the following error:
```
Logger: homeassistant.config_entries
Source: config_entries.py:745
First occurred: 15:08:39 (3 occurrences)
Last logged: 15:14:48

Error occurred loading configuration flow for integration dyson_cloud: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)
Error occurred loading configuration flow for integration dyson_local: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.9/site-packages/libdyson/__init__.py)
```

**Comment by Kakise** [comment]
You should not install the cloud version, it is not maintained anymore. Please only use the local version. Uninstall the cloud and the local versions if you have both, and then reinstall the local version.
