### ISSUE TITLE
Incorrect units for sensor readouts

### ISSUE THREAD

**Issue by Anto79-ops** [shenxn/ha-dyson#137]
Hi,

Thank you again for your awesome work here! I just noticed a minot thing that I wanted to bring to your attention i think the units reported are incorrect for my all my fan (2xPure Cool Link, 1xHot + Cool, and 2xFormaldehy Hot+Cool)

For example, below is my pure hot cool sensor readout

Humidity 36 %
Nitrogen Dioxide 2 µg/m³
PM 10 0 µg/m³
PM 2.5 0 µg/m³
Temperature 22.55 °C
Volatile Organic Compounds 30 µg/m³

The units "µg/m³" is only applicable to PM10 and 2.5. VOC's should be ppb and NO2 should be ppb or ppm. BUT when i look at my history, the numbers are actually not even the units I mentioend above. Instead, they are Dyson's 0 to 10 scale, so to even say they ppb or ppm or µg/m³ would be also incorrect.

Anyways just thought I mentioned this

thanks again for you efforts in making the integration criticla for some users such as myself.

**Comment by Zelaf** [comment]
Closed mine (#148) so we can keep this one open. Hopefully we can find a solution to this in the future!
