### ISSUE TITLE
Possible wrongful calculation of particles

### ISSUE THREAD

**Issue by Zelaf** [shenxn/ha-dyson#148]
Hi! I got two air purifiers in my home, one Dyson Hot+Cool Link and one IKEA Starkvind Bord which is their side table. I have vastly different numbers when it comes to air quality and I'm starting to wonder if either of them could possibly be wrong. I'll include a screenshot to show it!

![image](https://user-images.githubusercontent.com/10819462/179127988-5329b8d9-b11f-46ab-b24a-cb80b2328ebe.png)

**Comment by Anto79-ops** [comment]
This could be related to my post here.

https://github.com/shenxn/ha-dyson/issues/137#issue-1236022516

It's possible it's outputting Dyson 0 to 10 scale

**Comment by Zelaf** [comment]
Ah I see, so instead of reporting the actual number it's a scale from 1 to 10 of how the air quality is?

**Comment by Anto79-ops** [comment]
I believe it is but if it reports a number greater than 10 or 12 then I'm incorrect

**Comment by Zelaf** [comment]
I tried holding a lighter to the back of the fan by the sensor and it didn't go above 9. I think I need to try something that'll set of the sensor more.

**Comment by Zelaf** [comment]
Copy of #137 so closing this.
