### ISSUE TITLE
Possible to get device token from dyson local?

### ISSUE THREAD

**Issue by monsieurlatte** [shenxn/ha-dyson#15]
I noticed that when I setup Dyson Cloud that Dyson Local was created, so guessing you're able to pull in the token, is it possible for us to see that token so that we can save that for future use?

**Comment by eiddor** [comment]
If you're talking about the device credentials, you can use the `get_devices.py` script from this repo: https://github.com/shenxn/libdyson

**Comment by shenxn** [comment]
If you want to pull out the credential info directly from your HA instance, go to your configuration directory, then open `.storage/core.config_entries`. You'll be able to find it. Note that in version 0.6.1, you can now calculate the credential from WiFi password so actually you don't need to save that. You can always get that even without Dyson cloud.
