### ISSUE TITLE
Not all feature controls are exposed to HA for Pure Cool Link

### ISSUE THREAD

**Issue by lifebound** [shenxn/ha-dyson#152]
I have a Dyson Pure Cool Link.

The phsyical remote control exposes:
Power
'Auto'
Fan Speed
Sleep Timer
Oscillation
Night Mode

The only control I have in HA is Power.
Night mode, Air Quality sensitivity, and Continuous monitoring are exposed as 'configuration' items, but I can't control anything else that way.

I don't know if the problem is in the HA implementation, or the underlying library, unfortunately. I can provide any logs you might need.

**Comment by erd82** [comment]
Hi @lifebound, I had a similar issue that I could not found further controls. But they are there if you go into the details of the main entity. See https://github.com/shenxn/ha-dyson/issues/154

And if you are Using the latest mushroom frontend integration, you can control the fan speed and oscillation (it it works) like this:
![mushroom fan with dyson](https://user-images.githubusercontent.com/63564291/184536794-d3393105-d356-4546-bd88-94f3bb6e2e2b.gif)

Sleep timer is not available indeed and it never worked for me. But this you can easily automate in Home Assistant.
Does this help? If so, please close the issue.

**Comment by erd82** [comment]
BTW: For the sleep timer there is a service "Dyson Local: set_timer" available, so that you can send a new timer to the device.
