### ISSUE TITLE
TP09: Switch "Automatic Mode" missing

### ISSUE THREAD

**Issue by erd82** [shenxn/ha-dyson#154]
Hello, in the past I had the Dyson Purifier Cool (TP07), which I connected using this integration.
After a repair of the TP07, Dyson could only provide me a Dyson Purifier Cool Formaldehyde (TP09) as replacement.
Now I connected this TP09.

Now I am missing the switch for the **automatic mode**.
![image](https://user-images.githubusercontent.com/63564291/184492833-2566962b-83f3-4304-bcf3-509e7896c916.png)

Is there a chance to get the switch active?

Cheers, red

**Comment by Anto79-ops** [comment]
I beleive you have to click on the button "Dyson Fan" and auto will appear in a drop down menu.

**Comment by erd82** [comment]
Nope, no dropdown, no auto mode.

These are the entities that are available in Home Assistant:
![image](https://user-images.githubusercontent.com/63564291/184504502-c791e1fb-107c-4091-8780-24ffe78cd11e.png)

BTW: The formaldehyde sensor (which is specific to this device) is even not available.

**Comment by Anto79-ops** [comment]
It's kind of buried but it should be there. This is also a formaldehyde machine but I don't see formaldehyde numbers either. 

![Screenshot_20220813-135323.png](https://user-images.githubusercontent.com/79593761/184508871-51acbc26-e3cb-45b5-b8c3-448d8bcc0d6b.png)

**Comment by erd82** [comment]
Hi @Anto79-ops, you made my day!! 

I really found the dropdown you've mentioned. It was a bit hidden. Therefore I just attach this little instruction as a gif for others that even don't find it. 
![dyson auto mode](https://user-images.githubusercontent.com/63564291/184535990-4dad9555-d587-4643-a74e-b1ae171d76f9.gif)

Thanks!!

**Comment by erd82** [comment]
And for people who are looking for a way to switch on the auto mode:
service fan.turn_on provides some settings to turn on the auto mode, e.g.
```service: fan.turn_on
data:
  preset_mode: Auto
target:
  entity_id: fan.dyson_fan
```
or
![image](https://user-images.githubusercontent.com/63564291/184557798-8c5c89fb-ce62-4b03-9469-ec46ea7d447e.png)

**Comment by strohganoff** [comment]
The provided solution seems more like a workaround. Could we get an actual entity to set/toggle the preset mode without having to go into the device settings or creating an automation?
