### ISSUE TITLE
Problem on HA 2022.11.1

### ISSUE THREAD

**Issue by skybarberom** [shenxn/ha-dyson#169]
Hello,

just upgraded HA to 2022.11.1 but Dyson integration stopped working.
On the console I can read the following

`
2022-11-04 08:11:14.739 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Pure Cool (2021) for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 498, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/dyson_local/__init__.py", line 135, in async_unload_entry
    device = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
KeyError: 
`

**Comment by nmaitland** [comment]
I have the same issue since the upgrade. I uninstall and now when I try to reinstall I get

```
`Logger:` homeassistant.config_entries
Source: config_entries.py:809
First occurred: 13:36:05 (4 occurrences)
Last logged: 13:47:15

Error occurred loading configuration flow for integration dyson_cloud: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.10/site-packages/libdyson/__init__.py)
Error occurred loading configuration flow for integration dyson_local: cannot import name 'DysonPurifierHumidifyCoolFormaldehyde' from 'libdyson' (/usr/local/lib/python3.10/site-packages/libdyson/__init__.py)
```

**Comment by engloy** [comment]
I encountered a similar problem. Solved it by unplugging the fan from the mains, waiting for about 20 seconds before plugging it back in. Worked right after.

**Comment by skybarberom** [comment]
> I encountered a similar problem. Solved it by unplugging the fan from the mains, waiting for about 20 seconds before plugging it back in. Worked right after.

I confirm that it is ok now.
