### ISSUE TITLE
Dyson Purifier Humidify Cool Formaldehyde (358K) not supported

### ISSUE THREAD

**Issue by lucaconlaq** [shenxn/ha-dyson#177]
I've recently got a new Purifier Humidify Cool Formaldehyde, it doesn't work out of the box with this integration.
I played around a little bit and discovered that it's due to the fact that the device `device_type` is `358K`.

With the following hack, everything works great in HA.

```
def get_device(serial: str, credential: str, device_type: str):
    return DysonPurifierHumidifyCoolFormaldehyde(serial, credential, "358K") 
```

I wanted to let you know.
Thanks for sharing this integration.

**Comment by MarcusKapun** [comment]
Thx @lucaquerella - can you let me know how the hack works (e.g. where to insert etc)? Again, thanks!

**Comment by BerlinBased** [comment]
> I've recently got a new Purifier Humidify Cool Formaldehyde, it doesn't work out of the box with this integration. I played around a little bit and discovered that it's due to the fact that the device `device_type` is `358K`.
> 
> With the following hack, everything works great in HA.
> 
> ```
> def get_device(serial: str, credential: str, device_type: str):
>     return DysonPurifierHumidifyCoolFormaldehyde(serial, credential, "358K") 
> ```
> 
> I wanted to let you know. Thanks for sharing this integration.

I´m also interested in this hack but didn´t found the way to add the lines of code you shared. Please share the destination, thank you in forward!

**Comment by mattdevo1** [comment]
I'm having the same issue with device_type 438K (which is also not supported). Would love guidance on how to implement this hack.

**Comment by tinybighuman** [comment]
Yeah same here, interestingly 438E paired fine, but 438K did not.

**Comment by Trabbi1999** [comment]
I think he inserted/changed it somewhere in /config/custom_components/dyson_local

But I cannot find the same code as written above. There is something similar in config_flow.py starting in Line 207:

![grafik](https://user-images.githubusercontent.com/101253671/214710295-72e2fdc4-34e9-4beb-a623-536415b39faa.png)


I tried to change CONST_DEVICE_TYPE in const.py to 358K and 358E (the 358E was reported by my Homebridge instance, tried this value aswell), but both were not working. @lucaquerella it would be aswesome if you could share some more details where we can find this code :)

**Comment by AlxSZP** [comment]
Everyone! I found a solution, buried in this thread:
https://github.com/shenxn/libdyson/pull/32#issuecomment-1399591550
@javemp wrote it, I followed it and now it's working:
to get this working:

1. fully uninstall existing integration and restart ha
2. reinstall the integration from hacs (do not restart ha yet) and modify your manifest.json file to change:
`“requirements”: [“libdyson==0.8.11”]`
to:
`“requirements": ["git+https://github.com/jezzab/libdyson.git@main#libdyson==0.9.0"],`
3. restart ha and install integration as per normal, you should now see purifier cool in the list of devices

huge thanks to @jezzab for his work

**Comment by mattdevo1** [comment]
> Everyone! I found a solution, buried in this thread: [shenxn/libdyson#32 (comment)](https://github.com/shenxn/libdyson/pull/32#issuecomment-1399591550) @javemp wrote it, I followed it and now it's working: to get this working:
> 
> 1. fully uninstall existing integration and restart ha
> 2. reinstall the integration from hacs (do not restart ha yet) and modify your manifest.json file to change:
>    `“requirements”: [“libdyson==0.8.11”]`
>    to:
>    `“requirements": ["git+https://github.com/jezzab/libdyson.git@main#libdyson==0.9.0"],`
> 3. restart ha and install integration as per normal, you should now see purifier cool in the list of devices
> 
> huge thanks to @jezzab for his work

Yes that hack works. But you don't need to uninstall and reinstall. You just need to change that line in manifest.json and restart HA.

**Comment by gonzolino69** [comment]
I also have the Dyson Purifier Humidify Cool Formaldehyde (358K) and can't connect it with this change either.

**Comment by dotvezz** [comment]
Unfortunately this integration is no longer maintained, but I've created a new fork and am actively working on the new Formaldehyde models. Have a look at #185 for more information, and let me know if you have any questions.

**Comment by lucaconlaq** [comment]
Sorry for the late answer. 
The new fork completely solve this and other issues. great job @dotvezz.
