### ISSUE TITLE
state class measurement and unit °C thus indicating it has a numeric value; however, it has the non-numeric value: off

### ISSUE THREAD

**Issue by haaino** [shenxn/ha-dyson#187]
Sensor sensor.pure_cool_link_temperature has device class temperature, state class measurement and unit °C thus indicating it has a numeric value; however, it has the non-numeric value: off (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by Aohzan** [comment]
I made a temp fix https://github.com/shenxn/ha-dyson/blob/311c6f1a9e6f713c0ac6202db1054c94a878eadf/custom_components/dyson_local/sensor.py

**Comment by Aohzan** [comment]
solved with https://github.com/Aohzan/ha-dyson

**Comment by nhulsch** [comment]
@Aohzan can you open a PR with your fix in this repo? https://github.com/libdyson-wg/ha-dyson
They forked the integration to maintain it (see #185 )

**Comment by haaino** [comment]
I was wondering if there was progress on this issue? That would be great 😊

**Comment by dotvezz** [comment]
This has been solved in https://github.com/libdyson-wg/ha-dyson (thanks to @nhulsch and @Aohzan!). The readme on the new project explains how to migrate your configuration over, so feel free to check it out or let me know if you have any questions @haaino!
