### ISSUE TITLE
Support for Dyson Pure Humidify+Cool

### ISSUE THREAD

**Issue by ecostin** [shenxn/ha-dyson#19]
Shows up as model 358. It works pretty well, all sensors and controls, with the exception of the desired humidity setting, which is missing. Is it possible to add it? I can help with testing.

**Comment by ecostin** [comment]
Apologizes, it is written allready that the humidifier is not supported yet. One has to read that though first :)

**Comment by shenxn** [comment]
I'm starting working on this. Re-open this for progress tracking. I'll ping you for testing when I have an initial version.

**Comment by shenxn** [comment]
@ecostin version 0.7.0 now adds `humidifier` entity. Can you test that and see if everything is working as expected? Thanks

**Comment by ecostin** [comment]
Works perfectly for me, thank you @shenxn
