### ISSUE TITLE
Cannot add as an integration

### ISSUE THREAD

**Issue by ajcooper72** [shenxn/ha-dyson#21]
I've added both of the repositories to HACS (see screenshot) but when I search for them in the Integrations page they are not showing up.

I've restarted HA, but still nothing.

Am I missing a step?  I'm running 2021.3.3

![image](https://user-images.githubusercontent.com/15643760/110615134-fcb32180-818a-11eb-867f-95480f9b01ca.png)

**Comment by JakubMacoun** [comment]
Just a tip: try CTRL+F5 in your browser

**Comment by ajcooper72** [comment]
Apologies, I should really know better!
