### ISSUE TITLE
Feature Request: Fetch current position

### ISSUE THREAD

**Issue by lenwar** [shenxn/ha-dyson#23]
Hi,

It would be nice if we could 'fetch' the current angle of the (Pure Cool) fans.
In the latest release(s) (0.5.2 and up) we can manually set the fan to a specific angle/position and have it oscillate between two angles.

I don't know if it's possible of course. Maybe that info isn't fed back from the units. But it would be a 'nice to have'.

**Comment by shenxn** [comment]
Is this info available in the official mobile app?

**Comment by lenwar** [comment]
Yes.
The app can represent it visually. If for some reason it is 'out of sync' (if you do it manually on the unit itself, it sometimes shows it is determining it's position)

The screenshot below visually represents the actual direction.

![image](https://user-images.githubusercontent.com/3773186/110798110-1f703380-827a-11eb-93ef-8d6d68e036e8.png)

**Comment by shenxn** [comment]
I'll try to look into the protocol and see if it is possible.

**Comment by iceman23e** [comment]
@shenxn If you add the `angle_low` and `angle_high` attributes to the fan entity, this is what we'd need. When setting the angle as shown in the screenshot, both are equal. When oscillating, they are different. The official integration does this.

**Comment by shenxn** [comment]
@iceman23e Thanks. Will do.

**Comment by shenxn** [comment]
Added in version 0.6.0
