### ISSUE TITLE
Fan connection disconnect cause integration to become unresponsive 

### ISSUE THREAD

**Issue by googanhiem** [shenxn/ha-dyson#24]
Thanks @shenxn for this great work on this integration. Since the 2FA changes I been running this exclusively to run my fans, and it’s very good. 

One issue I’m experiencing is if the Dyson fan loses connection even temporarily, the integration becomes unresponsive,  the sensors cease updating and requires a system restart to work again. It provides no errors or warnings in the log. 

Reloading the integration doesn’t resolve the issue and results in the error “fan entity does not exist”. 

As there’s no log trail this is a tricky one to troubleshoot. Do you think you could add a warning for disconnections or timeouts?

**Comment by shenxn** [comment]
Can you enable debug log to see if you can find anything related? Add the following lines into `configuration.yaml`
```
logger:
  default: info
  logs:
    custom_components.dyson_local: debug
    libdyson: debug
```

**Comment by googanhiem** [comment]
Logs don’t shed too much light. 

When the issue happens it gives these messages 
```
2021-03-13 22:18:00 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 1
2021-03-13 22:18:02 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
```
Libdyson stops after this point but Dyson local continues unaware it failed.

**Comment by shenxn** [comment]
It seems `libdyson` successfully reconnects the device, it should be able to work again. There might be some bug in the code. Currently I'm on a business trip and don't have access to any Dyson device. I'll try to dig into this when I'm back home.

**Comment by googanhiem** [comment]
I tried reinitialising the integration a couple ways, but the issue persists. Basically the integration fails after around an hour following every reboot.

It also provides this error right after it fails now
`Error fetching environmental data: Failed to request environmental data`

Here are my findings after looking through the logs and troubleshooting,
- When the libdyson disconnects then appears to reconnect, the main issue seems to be that all state and environmental data stop transferring (the libdyson "New State" and "New Environmental State" json messages cease in the log, but the components "Finished fetching environmental data" message continues to appear after disconnections)
- I can still trigger service commands, but the HA state doesn't show it has changed (ex. fan.turn_on will turn the fan on, but it will continue to appear in HA with the off state)
- Both fans don't fail simultaneously, one fails then the next some time later, which leads me to believe my poor wifi connectivity with my fans is messing with the integration (due to being in a concrete building with lots of interference my fans disconnect then reconnects periodically daily).
- Seems like libdyson is losing connection due to error code 1 (which used to mean  "Connection refused - incorrect protocol version")

**Comment by shenxn** [comment]
@googanhiem Thanks for the info. The connect and disconnect logic in `libdyson` is a little bit complicated so there might be some bug. I'll try to refactor that and add some tests. I'll ping you for testing.

**Comment by googanhiem** [comment]
Cheers! Yeah, my limited python experience couldn't quite make sense of the connect logic, ha

I was able artificially trigger the error by rebooting my router if you want to test it yourself.

**Comment by iceman23e** [comment]
For what it's worth, I'm having this same issue. My HP04 stays connected for about an hour on average before `[libdyson.dyson_device] Disconnected with result code 1`. Only way I've found to restore control is a HA restart. Additionally, as googanhiem said, sometimes I can change the fan state without the front end changing, but most of the time, it's completely unresponsive.

**Comment by googanhiem** [comment]
Nice to know I'm not the only one. 

As its a connection issue there are two things I'd like to initially try with libdyson, (but since Hass OS went 64bit I can't find the site-packages),
- Changing the TIMEOUT to something higher than 10
- Changing the connect process to essentially restart the entire integration instead of just reconnecting. (it would take a little bit more time but it may be something to do with the MQTT broker or other elements that will allow it work)

If anyone knows where libdyson is in Hass OS, please tell me

**Comment by gee-jay-bee** [comment]
I'm also facing the same symptoms (sending commands works very intermittently but states don't update and a full restart is required to recover).

**Comment by googanhiem** [comment]
@gee-jay-bee And @iceman23e which fans do you have?
I'm on the Dyson Pure Cool (not link, desk and base... both are affected)

**Comment by gee-jay-bee** [comment]
1 x Pure Hot + Cool Link and some Pure Cool (desk and tower). All are affected it seems.

**Comment by iceman23e** [comment]
I have an HP04 Pure Hot+Cool.

**Comment by damiano75** [comment]
In my case it happens when I unplug the Dyson and plug it again. HA loses
the update from sensors and switches, if I toggle the on switch the Dyson
turns on, but the switch comes back to off position.
It's similar to the issue I had with the official integration, but at the
beginning this integration didn't have this issue: it was the primary
reason I switched to this integration

Il giorno mar 30 mar 2021 alle 17:20 Gord ***@***.***> ha
scritto:

**Comment by shenxn** [comment]
This integration is designed to handle reconnections. There has to be some problems in the code. I'm a little busy these days. I'll look into it when I got some free time.

**Comment by googanhiem** [comment]
Increasing the timeout didn't help. I'm now trying some changes to the reconnect logic, but no luck yet. The integration continues to fail after around 45 minutes following reboot.

**Comment by shenxn** [comment]
I've released version 0.9.0. @googanhiem Can you try if it fixes your problem? Currently I don't have access to any Dyson device to test.

**Comment by damiano75** [comment]
It seems it works for me: HP04

**Comment by shenxn** [comment]
Closing. Feel free to re-open if not working.
