### ISSUE TITLE
Local Discovery Times Out

### ISSUE THREAD

**Issue by codylawyer** [shenxn/ha-dyson#27]
I have three Dyson devices. Two were able to be successfully discovered and work great. My Dyson Pure Hot & Cool gets the error message: "Failed to find the device via discovery" when trying to configure it via integrations. 

The only message in the log is: 
2021-03-20 07:54:45 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Discovery timed out

Any suggestions? Thanks!

**Comment by shenxn** [comment]
Try unplug and replug your device. Discovery is not very stable and sometimes it just doesn't work.

**Comment by codylawyer** [comment]
That worked. Thanks again for all the hard work on this add-on!
