### ISSUE TITLE
Oscillation support for Pure Cool Link

### ISSUE THREAD

**Issue by leewestcott** [shenxn/ha-dyson#28]
Only part missing for me, otherwise this is perfect. Thanks for all the work that's gone into this.

**Comment by shenxn** [comment]
Can you find anything related in log?

**Comment by shenxn** [comment]
I think it should work. What is not working?

**Comment by leewestcott** [comment]
I don't have an entity for oscillation

**Comment by shenxn** [comment]
The oscillation control is inside the fan control panel. There is no separated entry for that.

**Comment by leewestcott** [comment]
And so it is, sorry I didn't see that.
