### ISSUE TITLE
Humidifier auto mode pure humidify and cool (model 358)

### ISSUE THREAD

**Issue by johnhoogeveen** [shenxn/ha-dyson#29]
Control of the humidifier parameter works great, but only works if you turn off auto mode.
Maybe just disable auto mode for the humidifier when a custom settings is required similar as the fanspeed control when changing the fan speed
There auto mode is turned off when I enable a custom speed.

Running version 0.8.1

**Comment by shenxn** [comment]
Try if the latest version fixes your problem.

**Comment by johnhoogeveen** [comment]
Just installed the latest version (0.10.0) and changing the humidifier parameter to another value turns off the auto mode.
That was exactly the idea, thank you!!
