### ISSUE TITLE
"tm" always added at the end of device name

### ISSUE THREAD

**Issue by Ulrar** [shenxn/ha-dyson#3]
Hi,

Not a huge deal, but by default my fan came on as "Dyson Pure Link™", which I then renamed to Bedroom fan. Now my entity is named "fan.bedroom_fantm" and I can't seem to be able to do anything about that tm at the end.

Apart from this minor naming issue everything is working like a charm and it's cloudless, many thanks !

**Comment by shenxn** [comment]
Version 0.4.0 fixes this. If your entity name is not changed, try remove and re-add your devices.
