### ISSUE TITLE
homekit?

### ISSUE THREAD

**Issue by chrisdrackett** [shenxn/ha-dyson#32]
This might not be the right place to ask, but I'm not able to get these fan entities to show up in HomeKit. Has anyone gotten that to work or know what the issue might be?

**Comment by shenxn** [comment]
Sorry but I have no idea. It depends on how the homekit integration loads entities.

**Comment by shenxn** [comment]
I don't have any apple device so it's a little hard to debug. If anyone is interested, feel free to provide more info or create a PR.

**Comment by johan-de-jong** [comment]
Homekit works just fine for me. I enabled the climate and fan domains.

![ACD6C7D3-16E8-44F9-B4BC-796DB24A7621](https://user-images.githubusercontent.com/38002717/118313545-28d48100-b4f3-11eb-896a-4ddb8492c46c.png)
![7DA87F22-582D-4DF5-9DB8-8F134846109E](https://user-images.githubusercontent.com/38002717/118313551-2b36db00-b4f3-11eb-9206-24ab607ad86c.jpeg)
![CC9AC143-46CF-482E-84C5-390C6E36A25A](https://user-images.githubusercontent.com/38002717/118313555-2bcf7180-b4f3-11eb-9138-b40f8394d524.jpeg)
![A47DA02F-46D0-46BF-9091-5D34F54E4403](https://user-images.githubusercontent.com/38002717/118313557-2c680800-b4f3-11eb-9ef3-1cf5d2c23fd0.png)

**Comment by chrisdrackett** [comment]
@johan-de-jong curious what you have in your config, here is what I have:

```
- name: Climate
  port: 56335
  filter:
    include_domains:
      - climate
      - fan
    include_entity_globs:
      - fan.*
      - climate.*
```

I get my thermostat in via this, but none of my fans:

for example `fan.bedroom`

**Comment by chrisdrackett** [comment]
I wonder if there is something different between the pure hot and cool and my fan which is just a "pure cool"?

**Comment by chrisdrackett** [comment]
I got this working, pretty sure the issue is not related to this repo so I'm closing. I had to change:

https://gist.github.com/chrisdrackett/468b6282b72420b1d136ab7cdfa8829e
to
https://gist.github.com/chrisdrackett/ea7855a404b49393315da1612fa9735d

¯\_(ツ)_/¯

**Comment by johan-de-jong** [comment]
> I wonder if there is something different between your `527` and my `475` (the model number that shows up for me in hass)

527 is the model number. In my case: https://www.dyson.nl/luchtbehandeling/luchtreinigers/dyson-pure-hot-cool/zwart-nikkel
