### ISSUE TITLE
Dyson pure Hot+Cool missing entity (fan speed 1 to 10, oscillation on/off) ? or feature request

### ISSUE THREAD

**Issue by gbo35** [shenxn/ha-dyson#35]
Hi Thanks for your dev :)

(sorry for my english)

I add my Dyson pure Hot/Cool with your instruction and nice work. But, i not found this entity : 

- Fan speed 1 to 10 (no auto mode)
- Osicllation (On/Off)

This normal ? Or this function has not implemented ?

Device :
![image](https://user-images.githubusercontent.com/30604570/113881599-de0d6e00-97bc-11eb-90de-984f27669342.png)

Entity :+1: 
![image](https://user-images.githubusercontent.com/30604570/113881814-10b76680-97bd-11eb-8528-e9cc63272675.png)

Regard !

**Comment by shenxn** [comment]
You should click the fan panel then you'll find speed and oscillation settings in the popup panel.

**Comment by gbo35** [comment]
oh...
thank you ! :D
