### ISSUE TITLE
Missing on/off switch

### ISSUE THREAD

**Issue by Pakawat75** [shenxn/ha-dyson#39]
I just updated from version 0.8.1 to 0.11.0. The on/off switch become unavailable. and oscillating as well.
My device is Dyson Pure Cool (TP04)

**Comment by shenxn** [comment]
Can you find anything related in the log?

**Comment by Pakawat75** [comment]
Nothing there. Here is entities that available. By the way, I really new to HA with really noob here
![Entities](https://user-images.githubusercontent.com/80138215/115450402-0b8afa80-a246-11eb-96b2-bbdd6b76fd03.jpg)

**Comment by Pakawat75** [comment]
By remove "AirQualityTarget.OFF: "off"" have bring back the on/off switch
![Screenshot (2)](https://user-images.githubusercontent.com/80138215/115915068-fbb92380-a49c-11eb-92e3-3f571a281f4f.png)
![Screenshot (4)](https://user-images.githubusercontent.com/80138215/115915160-20150000-a49d-11eb-8f06-fd90e8a5f090.png)

**Comment by shenxn** [comment]
This seems to be related to libdyson version. Can you try to reinstall the custom components? Also, if you're using `ha-dyson-cloud` as well, please make sure the major version of both components are the same (e.g. both on version 0.11.x).

**Comment by Pakawat75** [comment]
Yes, by reinstall custom components solved the issue. Thank !!!!
