### ISSUE TITLE
Error in automation : state 'fail' cannot be processed as a number

### ISSUE THREAD

**Issue by Perlnx** [shenxn/ha-dyson#40]
Hello,
I've create automation numeric state trigger base on air quality, This is configuration.

platform: numeric_state
entity_id: air_quality.dyson_tp04_living_room_air_quality
for: '00:10:00'
above: '50'

Automation works fine, but I got random warning message from home assistant log.

----------------------------------------------------------------------------------------------
Logger: homeassistant.components.homeassistant.triggers.numeric_state
Source: components/homeassistant/triggers/numeric_state.py:163
Integration: Home Assistant Core Integration (documentation, issues)
First occurred: 10:59:10 AM (1 occurrences)
Last logged: 10:59:10 AM

Error in '[Stairway] Attic Fan Turn Off' trigger: In 'numeric_state' condition: entity air_quality.dyson_tp04_living_room_air_quality state 'fail' cannot be processed as a number

----------------------------------------------------------------------------------------------

When message appear air quality not reach 50 yet (It's just 3)
I not sure is there any message other than integer send out from Air Quality state ?

**Comment by shenxn** [comment]
Normally it won't. It only gives state `fail` when the device reports `FAIL` as the value of air quality. To me I think it means that there is something wrong with the sensor.

**Comment by Perlnx** [comment]
I see, That's why the automation got error because it have string "fail" message.
Last logged: 6:58:26 AM

![Capture](https://user-images.githubusercontent.com/13845123/115327707-98d43d80-a1b9-11eb-85f3-533557c0a47f.JPG)

I not sure which sensor, fan sensor ?
This is a new device, just bought 4 months ago.

**Comment by shenxn** [comment]
As long as the fail state lasts for only a short period of time, I think it is fine. You can try using template to filter out fail states. For now, I'm not going to change anything unless there are more users reporting this.
