### ISSUE TITLE
Dyson local - no way to actually turn Pure Cool Link Desk on or off

### ISSUE THREAD

**Issue by mattcasey94** [shenxn/ha-dyson#45]
Hello,

Maybe I am missing something, but I have no way to actually turn the device on or off, control the power, osciliation or any of those options. Only options i have are night more or auto mode. Is this expected or is something not working with my install?

Attached screenshot:

![image](https://user-images.githubusercontent.com/62463197/117532485-affb9380-afdf-11eb-87f0-ab075c014434.png)

Any help appreciated
Matt

**Comment by shenxn** [comment]
The fan entity is missing. Can you check if you can find anything related in log?

**Comment by nicholasloek** [comment]
I have the same issue with my Cool Link, no fan control is showing up. Can't find anything in my logs. Looking further.
![CoolLink](https://user-images.githubusercontent.com/10201288/134844761-51b51e6b-5e47-4ce4-b180-15429d1b79a3.PNG)

**Comment by Flameeyes** [comment]
Sounds like the same as #13 (Minimum HA version 2021.3.0)
