### ISSUE TITLE
Pure hot + cool link | Missing oscillation and sleep timer features.

### ISSUE THREAD

**Issue by BrianVEA** [shenxn/ha-dyson#53]
Good day, first of all thank you for creating and maintaining this project, I have recently started using home assistant and this project has been a wonderful addition to my home automation.

All features on displayed on the screenshot below have been working wonderfully, sadly I have been unable to find the oscillation option or the sleep timer that I do have access through on my Dyson remote or the official Dyson app. 
From my little python knowledge it seems that these two settings are part of the project and I have also seen the oscillation and sleep timer options in screenshots of other peoples issues for their devices.

Thank you in advance and my apologies if I have missed something very obvious or if I missed an already resolved issue for this.

SSID: DYSON-PT4-EU-XXXXXXXX-455

![chrome_rH77Clw9CW](https://user-images.githubusercontent.com/21298477/119232719-876ab200-bb26-11eb-9489-84b74061caf7.png)
![chrome_aYHw8UHypU](https://user-images.githubusercontent.com/21298477/119232721-89cd0c00-bb26-11eb-84f6-163d541ea78e.png)

**Comment by shenxn** [comment]
Click on the fan entity and you should be able to see the oscillation option in the popup card. As for the sleep timer, use the service `dyson_local.set_timer`. To be able to set timer in UI, you'll need things like scripts, input select, or input number.

**Comment by BrianVEA** [comment]
Can't believe I overlooked that, found the oscillation feature thank you so much and apologies for the trouble!
