### ISSUE TITLE
"angle_low" and "angle_high" entities not showing up for TP04

### ISSUE THREAD

**Issue by mont3crysto** [shenxn/ha-dyson#61]
Per title the quoted entities are not showing up anymore on Home Assistant and cannot be changed through its API (eg. with Node-red).

Below the versions I used to test it:

Home Assistant version: 2021.3.4 | 2021.7.0b0
Dyson model: Pure Cool TP04
HACS version: 1.13.2
Dyson Local version: 0.14.0 | 0.15.0

Let me know if there's something else I can provide to you; thanks.

**Comment by shenxn** [comment]
Was it working before? If so, which version? Thanks.

**Comment by mont3crysto** [comment]
Unfortunately in these months I couldn't find any time to investigate the issue further, but it's currently working now (on latest version of both Home Assistant and ha-dyson), so... all good :)

Thank you very much.
