### ISSUE TITLE
Air_quality entity is deprecated

### ISSUE THREAD

**Issue by DeGelder** [shenxn/ha-dyson#62]
The entity air_quality will be deprecated and should be replaced with seperate sensors.
Source:
- https://github.com/home-assistant/architecture/discussions/573
- https://developers.home-assistant.io/docs/core/entity/air-quality/

**Comment by shenxn** [comment]
Thanks for the info! Will do.

**Comment by Jc2k** [comment]
A further heads up: In dev there were device classes added for measurements that were previously part of air quality:

* https://github.com/home-assistant/core/pull/54075
* https://github.com/home-assistant/core/pull/55050

Cheers

**Comment by Kakise** [comment]
Fixed by PR #69 !
