### ISSUE TITLE
Dyson Local integration error - Retrying setup: None

### ISSUE THREAD

**Issue by Ripper2909** [shenxn/ha-dyson#63]
Hi,

First of all, thank you for this great integration which allows us to use the Dyson fans locally (as it should be by default in a perfect world :D)
Unfortunatly, my Dyson Local integration encounters an error about once to twice a week. (since I installed it first, about 1 month ago)
The integration crashes and shows the message "Retrying setup: None".
From there, my Dyson HP04 is still online, but becomes unreachable from the integration.
The only thing that solves it is to delete the integration and add the HP04 again (I don't even have to reboot the dyson fan, so I think the issue comes from the integration)
I always choose the manual configuration, and the device type 527.

Dyson version is at latest (auto updates are disabled just in case)
Running core-2021.7.4, supervisor-2021.06.8 (stable channel) on HassOS 6.1 on an Intel NUC.
Do you have any ideas on how to solve this issue please ?

Next time this happens I will try to reboot the fan and hassio without deleting and re adding the integration and keep you posted !

Thanks !

**Comment by shenxn** [comment]
It seems there is some problem with the reconnect logic. I'll look into it.

**Comment by DarKOrange75** [comment]
Hi, same issue here, the integration has definitively stopped working and shows the same message as above in the integration panel "Retrying setup: None"

**Comment by Ripper2909** [comment]
Hey ! At least I'm not alone in this
I found since then that it often happens when the Dyson HP04 temporarily disconnects from the network...
The fault is for sure on Dyson but maybe this case could be handled in this wonderful custom integration ?

**Comment by phrostt** [comment]
I dont know if its at all related, but I had the same issue so deleted the integration thinking I just need to redo it. Now I keep getting failed to connect when trying to add a dyson local integration.

**Comment by Ripper2909** [comment]
Alright, just to keep you updated, I have some news about this.
According to my tests, the issue comes from the HP04 which disconnects from the LAN about once or twice a week.
So I made a dirty fix to fix it automatically :
alias: Thermostat Reviver
description: should restore last settings and shoudnt restart hassio...
trigger:
  - platform: state
    entity_id: air_quality.pure_hot_cool_air_quality
    to: unavailable
condition: []
action:
  - service: notify.mobile_app_galaxy_phone
    data:
      title: Info
      message: Thermostat reviver triggered
  - service: notify.mobile_app_chromeos
    data:
      title: Info
      message: Thermostat reviver triggered
  - service: switch.turn_off
    target:
      entity_id: switch.bedroom_dyson_hp04_outlet
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id: switch.bedroom_dyson_hp04_outlet
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: shell_command.dyson_integration_restart
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: homeassistant.restart
mode: single

alias: homeassistant_start
initial_state: true
trigger:
  - platform: homeassistant
    event: start
action:
  - service: browser_mod.close_popup
  - delay:
      seconds: 1
  - service: frontend.reload_themes
  - delay:
      seconds: 1
  - service: fan.turn_on
    target:
      entity_id: fan.pure_hot_cool
mode: single

The only issue here is that : at the time of the HP04 disconnection, even if the integration is reloaded after making the HP04 available once again on the LAN, the HA Core Integration needs to be reloaded. Which is strange because the integration reload should do the work, as it did for reloading the ZHA and the AppleTV integration. I didn't find a better yet, any improvement idea please ?

**Comment by Kakise** [comment]
There have been many updates that should have fixed this problem. I daily drive this very integration and didn't see it occurring to me. I'll reopen the issue if the problem keeps happening.
