### ISSUE TITLE
"Failed to find the device using discovery" 

### ISSUE THREAD

**Issue by pcambra** [shenxn/ha-dyson#68]
I've been able to use https://github.com/shenxn/libdyson and to figure out how to get the serial and credential from my HP04, but when I try to add it from the "Dyson local" integration, I get "Failed to find the device using discovery", I've tried reinstalling the HACS integration, restarting, etc, nothing seems to work.
Any pointers?

**Comment by ctborg** [comment]
Thank you pcambra. I added the IP of the device to the Host field, along with the wi-fi connection information and it worked.

**Comment by jchhenderson** [comment]
I am also having this problem - where do you add the IP?
