### ISSUE TITLE
Issues entering credentials in the integration page?

### ISSUE THREAD

**Issue by kintaroju** [shenxn/ha-dyson#7]
I've tried to fill all the information below in the sample screenshot below, but for the life of me what do you use for "credential". I've tried my dyson email, password, no luck?

![image](https://user-images.githubusercontent.com/29717036/110011000-c598c800-7cd3-11eb-9efa-a1f6328caadd.png)

**Comment by eiddor** [comment]
See #5 for credential information.  The serial number can be obtained from the mobile app.

**Comment by monsieurlatte** [comment]
I too am in this situation.  I have tried to run commands from my mac but I'm just not having any luck, I manage to run the pip install and I think it's there and working but when I run python3 dyson.py it doesnt work.

**Comment by shenxn** [comment]
See the up-to-date README. I've added some instructions.

**Comment by ghostbitmeta** [comment]
https://community.home-assistant.io/t/dyson-pure-cool-link-local-mqtt-control/217263

See the section of using the script to convert your WiFi password. Not sure why this integration doesn't do the hash conversion for you.

**Comment by shenxn** [comment]
> https://community.home-assistant.io/t/dyson-pure-cool-link-local-mqtt-control/217263
> 
> See the section of using the script to convert your WiFi password. Not sure why this integration doesn't do the hash conversion for you.

@ghostbitmeta I didn't even know that it is possible to simply calculate MQTT password from WiFi password. Thanks for pointing that out. I'll consider adding that to make the setup process easier.

**Comment by shenxn** [comment]
In version 0.6.1 you can now set up using WiFi SSID and password.

**Comment by monsieurlatte** [comment]
> In version 0.6.1 you can now set up using WiFi SSID and password.

whoa!  Really?  That's awesome!
