### ISSUE TITLE
cannot install v0.15.0 from custom repo into HA 2021.11.2

### ISSUE THREAD

**Issue by jchhenderson** [shenxn/ha-dyson#71]
Hi,

I have added the custom repo into HACS, but installing doesn't do anything - I do I have other things installed OK).

Can anyone assist?

**Comment by Kakise** [comment]
Hello,

Can you try updating to the 0.16.0 release and tell me if it works now ?

**Comment by jchhenderson** [comment]
0.16.0 works fine
thanks!

**Comment by Kakise** [comment]
No problem !
