### ISSUE TITLE
Add a ha-dyson custom-card 

### ISSUE THREAD

**Issue by xbgmsharp** [shenxn/ha-dyson#76]
Sample custom-card to display ha-dyson detail information including attributes
https://gist.github.com/xbgmsharp/03e6b8aa7fb00cc98584794c7760fd0c

**Comment by Kakise** [comment]
It's outside of the scope of this project. ha-dyson aims to provide an integration that can be built on. However hmu if you end up making this into a plugin, I'll be glad to link it in the readme.
