### ISSUE TITLE
Entity fan.pure_hot_cool implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by drizuid** [shenxn/ha-dyson#78]
NOTE: everything works fine from my tests, this said to report it to the author so I am.

WARNING (MainThread) [homeassistant.helpers.entity] Entity fan.pure_hot_cool (<class 'custom_components.dyson_local.fan.DysonPureCoolEntity'>) implements device_state_attributes. Please report it to the custom component author.

Version | core-2021.12.0

dyson_local and dyson_clolud are both pulled from git main branch about 5 minutes ago.

**Comment by drizuid** [comment]
minor update: i found that everything is working as usual except the air quality

![image](https://user-images.githubusercontent.com/40674481/145690656-f8f32954-7606-460e-a3b0-f7489b300ce0.png)
![image](https://user-images.githubusercontent.com/40674481/145690666-1f95d152-795c-431d-b8fa-18db521319ac.png)

**Comment by Flameeyes** [comment]
I've removed the air quality platform from ha-dyson with my pull request last month, replaced by separate air quality sensors, as per Home Assistant best practices.

I did miss the device_state_attributes deprecation though, so I didn't realize that needed to be fixed. I've got a change for it already, sending the pull request in a moment.

**Comment by drizuid** [comment]
Makes sense, thanks for the reply! have a super day, i'll leave this open for your PR to close once merged.

**Comment by Kakise** [comment]
Merged !
