### ISSUE TITLE
Devices Type ?

### ISSUE THREAD

**Issue by lolongan** [shenxn/ha-dyson#8]
I have install shenxn/ha-dyson using HACS.
Then, when trying to set-up the Dyson_Local integration, in the dropdown list "Device Types", I can see 
"360 eyes ...", 
"Pure Cool Link", 
"Pure Humidity + Cool", 
etc.
but no "Pure Hot + Cool".
Do you know how to make this last choice appear or how to enter it or is it possible to setup within configuration.yaml (with which parameters) ?
Thanks.

<img width="393" alt="Capture d’écran 2021-03-05 à 14 14 13" src="https://user-images.githubusercontent.com/76393476/110120605-8b0b5a00-7dbd-11eb-8d61-cbe4712775f4.png">

**Comment by shenxn** [comment]
I forgot to add those device types into the list. Will fix that soon.

**Comment by krazar** [comment]
Same here. I also have a pure hot+cool link.
Cheers

**Comment by lolongan** [comment]
> Same here. I also have a pure hot+cool link.
> Cheers

Did you succeed to connect ? 
I have a Pure Hot+Cool and tried to use Pure Cool and Pure Humidity+Cool but both did not work. 
Have to wait for Shenxn to add these device types into the list.

**Comment by shenxn** [comment]
Version 0.4.0 should fix this.

**Comment by lolongan** [comment]
> Version 0.4.0 should fix this.

Awsome, I have succeeded now to setup everything.
Fēicháng gǎnxiè ni, @shenxn
