### ISSUE TITLE
Support for Forwards/Reverse Air Direction

### ISSUE THREAD

**Issue by jerobertson** [shenxn/ha-dyson#80]
Is it possible to supprot forwards/reverse air direction?

I currently own a Dyson DP04 which, on the remote (and app) has the ability to point the air direction either forwards, or behind the fan. This doesn't seem possible with this library? Would this be possible to implement?

**Comment by qqaatw** [comment]
Maybe [this](https://github.com/shenxn/ha-dyson/issues/75#issuecomment-991919715) helps?
