### ISSUE TITLE
戴森cloud输入手机号提交显示Unknown error occurred

### ISSUE THREAD

**Issue by xmasrain** [shenxn/ha-dyson#83]
请问大佬现在国内的设备还能获取到Credentials吗？

**Comment by Kakise** [comment]
Hello, could you please rewrite your issue in English ?

**Comment by xmasrain** [comment]
same problem here. Thanks for your attention

https://github.com/shenxn/libdyson/issues/20

**Comment by Kakise** [comment]
Fixed ! :)
