### ISSUE TITLE
Failed to Connect to dyson cloud (issue with libdyson)

### ISSUE THREAD

**Issue by Spross1** [shenxn/ha-dyson#84]
I've tried everything I can think of to get this integration working but nothing will do it. The logs are showing that the device is being found but I'm not sure why it won't connect. I've logged out of the app on my phone to see if that would fix it as well as restarting the Dyson fan itself. I can't get the Dyson cloud or Dyson local integration working for whatever reason. The logs don't give a ton of info but here is the section for reference:

2021-12-19 15:37:29 DEBUG (zeroconf-ServiceBrowser-_360eye_mqtt._tcp-_dyson_mqtt._tcp-362) [custom_components.dyson_local.config_flow] Found device at 192.168.1.104
2021-12-19 15:37:30 DEBUG (Thread-111) [libdyson.dyson_device] Connected with result code 5
2021-12-19 15:37:30 DEBUG (Thread-111) [libdyson.dyson_device] Disconnected with result code 0
2021-12-19 15:37:30 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: 
2021-12-19 15:37:44 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: 

my Dyson fan does connect via homebridge, but I deleted the configuration thinking that maybe that could be the issue. Still no luck though. Any help is greatly appreciated!

**Comment by Kakise** [comment]
Hello,

What is the device that you are trying to connect ?

**Comment by Spross1** [comment]
> Hello,
> 
> What is the device that you are trying to connect ?

The device is a Dyson HP04 Heat+Cool purifier. I use the Dyson link app and there’s no wifi information on the device anywhere. I have the credentials and serial number from my installation in Homebridge but when I use that same information in home Assistant for Dyson local it doesn’t actually set up for some reason.

**Comment by stefanzierpersonal** [comment]
@Spross1 I have the same device. The WiFi information is on a sticker under the filter. Push the two buttons on the gray filter and pull it up. You'll see it. The SSID is something like `DYSON-ABC-US-A1B2B3B4-123` and the password is 8 lowercase letters.

**Comment by Spross1** [comment]
I just double checked because I’d seen someone mention that originally but maybe you can help me find it. I don’t see it anywhere. I’ll add some pics for reference 
![image](https://user-images.githubusercontent.com/87457720/147167331-abd7ebab-826a-47ae-8d0d-bfedef1ed91c.jpg)
![image](https://user-images.githubusercontent.com/87457720/147167356-f3c37c74-34b4-4136-b853-9f52289b65e3.jpg)

**Comment by Spross1** [comment]
> @Spross1 I have the same device. The WiFi information is on a sticker under the filter. Push the two buttons on the gray filter and pull it up. You'll see it. The SSID is something like `DYSON-ABC-US-A1B2B3B4-123` and the password is 8 lowercase letters. Note that the serial number displayed in the Dyson app is missing the last 3 digits of this SSID.

I'll also add some photos of the app when I click "change network": 
![IMG_7879](https://user-images.githubusercontent.com/87457720/147170158-502cb501-09f0-4062-b4cd-86c725ec11f9.PNG)
![IMG_7880](https://user-images.githubusercontent.com/87457720/147170170-5e1a783c-0b97-4b49-a578-ef80ebea8dc8.PNG)
![IMG_7881](https://user-images.githubusercontent.com/87457720/147170174-3dc04472-a03c-4d53-ab73-da63d9ce510c.PNG)

**Comment by Spross1** [comment]
could the problem be with my libdyson? this is an error in the log that I see:

"2021-12-22 18:33:20 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of libdyson==0.8.9"

**Comment by damiano75** [comment]
> Dyson HP04 Heat+Cool purifier

I have the same device, what I understand is that this device uses bluetooth connection to set it by app during the first connection to your wi-fi network, so you cannot setup using device WIFI information

**Comment by Kakise** [comment]
There seem to be a problem with libdyson and the connection to the cloud, Dyson must have changed its API once again, I am pinning this issue until I resolve the bug

**Comment by engloy** [comment]
> There seem to be a problem with libdyson and the connection to the cloud, Dyson must have changed its API once again, I am pinning this issue until I resolve the bug

I just upgraded my Home Assistant today to the latest version on my Raspberry Pi and am facing the same issue. My Dyson fan wouldn't work on Home Assistant. I tried removing Dyson Local from HACS and reinstalling but couldn't connect to my fan (I didn't have this problem before). Tried the Dyson Cloud route and managed to get past the authentication page but had an error connecting to the fan with a libdyson.exceptions.DysonInvalidAuth in the log.

**Comment by engloy** [comment]
> > There seem to be a problem with libdyson and the connection to the cloud, Dyson must have changed its API once again, I am pinning this issue until I resolve the bug
> 
> I just upgraded my Home Assistant today to the latest version on my Raspberry Pi and am facing the same issue. My Dyson fan wouldn't work on Home Assistant. I tried removing Dyson Local from HACS and reinstalling but couldn't connect to my fan (I didn't have this problem before). Tried the Dyson Cloud route and managed to get past the authentication page but had an error connecting to the fan with a libdyson.exceptions.DysonInvalidAuth in the log.

I downgraded to 0.16.1 and then upgraded back to 0.16.2 and was able to set up successfully via the Dyson Local integration. Didn’t check Dyson Cloud though.

**Comment by engloy** [comment]
> > > There seem to be a problem with libdyson and the connection to the cloud, Dyson must have changed its API once again, I am pinning this issue until I resolve the bug
> > 
> > 
> > I just upgraded my Home Assistant today to the latest version on my Raspberry Pi and am facing the same issue. My Dyson fan wouldn't work on Home Assistant. I tried removing Dyson Local from HACS and reinstalling but couldn't connect to my fan (I didn't have this problem before). Tried the Dyson Cloud route and managed to get past the authentication page but had an error connecting to the fan with a libdyson.exceptions.DysonInvalidAuth in the log.
> 
> I downgraded to 0.16.1 and then upgraded back to 0.16.2 and was able to set up successfully via the Dyson Local integration. Didn’t check Dyson Cloud though.

Looks like I spoke too soon. The integration worked fine until I upgraded HA core 2021.12.8. Now it’s stuck with the same issue again. Tried downgrading to 0.16.1 and upgrading back to 0.16.2. No success.

**Comment by MarkXUt** [comment]
I got same issue with brand new Dyson Pure Humidity+Cool, Model: Ph04
Firmware: ECG2PF.47.01.000.0005

Step1: got verification code
Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 1
Phone number: 186xxxxxxxx
Verification code: xxxxxx

Serial: K1G-CN-xxxxxxxx
Name: 卧室
Device Type: 358E
Credential: xxxxxxxx

Step 2: config integration manually but failed with "Failed to connect to device"
2022-01-16 11:27:11 DEBUG (zeroconf-ServiceBrowser-_360eye_mqtt._tcp-_dyson_mqtt._tcp-278) [custom_components.dyson_local.config_flow] Found device at 192.168.50.2
2022-01-16 11:27:12 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:12 INFO (MainThread) [libdyson.dyson_device] Connected to device K1G-CN-xxxxxxxx
2022-01-16 11:27:12 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:14 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:14 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:15 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:15 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:17 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:17 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:18 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:18 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:20 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:20 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:21 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:21 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:23 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:23 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:25 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:25 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:27 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:27 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:28 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:28 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:30 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:30 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:31 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0
2022-01-16 11:27:31 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7
2022-01-16 11:27:32 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device:

**Comment by GitPetri** [comment]
> I got same issue with brand new Dyson Pure Humidity+Cool, Model: Ph04 Firmware: ECG2PF.47.01.000.0005
> 
> Step1: got verification code Please choose your account region 1: Mainland China 2: Rest of the World Region [1/2]: 1 Phone number: 186xxxxxxxx Verification code: xxxxxx
> 
> Serial: K1G-CN-xxxxxxxx Name: 卧室 Device Type: 358E Credential: xxxxxxxx
> 
> Step 2: config integration manually but failed with "Failed to connect to device" 2022-01-16 11:27:11 DEBUG (zeroconf-ServiceBrowser-_360eye_mqtt._tcp-_dyson_mqtt._tcp-278) [custom_components.dyson_local.config_flow] Found device at 192.168.50.2 2022-01-16 11:27:12 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:12 INFO (MainThread) [libdyson.dyson_device] Connected to device K1G-CN-xxxxxxxx 2022-01-16 11:27:12 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:14 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:14 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:15 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:15 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:17 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:17 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:18 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:18 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:20 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:20 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:21 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:21 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:23 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:23 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:25 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:25 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:27 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:27 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:28 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:28 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:30 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:30 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:31 DEBUG (Thread-5) [libdyson.dyson_device] Connected with result code 0 2022-01-16 11:27:31 DEBUG (Thread-5) [libdyson.dyson_device] Disconnected with result code 7 2022-01-16 11:27:32 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device:

Same error code here https://github.com/shenxn/ha-dyson/issues/86

**Comment by albshin** [comment]
Dyson Cloud seems to use an older version of libdyson (0.8.7 vs 0.8.9) which [looks like it solves certificate related issues](https://github.com/shenxn/libdyson/releases/tag/v0.8.9). The package might just need a version bump. Also there needs to be a disclaimer about being logged out of the Dyson Link app. Authentication will fail if you're still logged in.

For anyone that wants to get your Dyson fan into HA, you can follow these steps as a workaround:

1. Clone [libdyson](https://github.com/shenxn/libdyson)
2. `cd` into the repository
2. Run `pip install -r requirements.txt` (or `pip3` depending on your OS)
3. **MAKE SURE YOU'RE LOGGED OUT OF THE DYSON LINK APP**
4. Run `python get_devices.txt` and complete the verification process
5. Take the Serial, Credential, and Device Type and setup the Dyson Local integration. You can find out what your device type is by referencing [this](https://github.com/shenxn/libdyson/blob/7b19d1c96c151eb876d8d8fbb3a4d5f2917b86b3/libdyson/const.py#L4). For example, I have a TP04 which gave me a device type of 438. Therefore the correct device type in the dropdown would be "Pure Cool Desk".

**Comment by GitPetri** [comment]
> Dyson Cloud seems to use an older version of libdyson (0.8.7 vs 0.8.9) which [looks like it solves certificate related issues](https://github.com/shenxn/libdyson/releases/tag/v0.8.9). The package might just need a version bump. Also there needs to be a disclaimer about being logged out of the Dyson Link app. Authentication will fail if you're still logged in.
> 
> For anyone that wants to get your Dyson fan into HA, you can follow these steps as a workaround:
> 
> 1. Clone [libdyson](https://github.com/shenxn/libdyson)
> 2. `cd` into the repository
> 3. Run `pip install -r requirements.txt` (or `pip3` depending on your OS)
> 4. **MAKE SURE YOU'RE LOGGED OUT OF THE DYSON LINK APP**
> 5. Run `python get_devices.txt` (or `python3` depending on your OS) and complete the verification process
> 6. Take the Serial, Credential, and Device Type and setup the Dyson Local integration. You can find out what your device type is by referencing [this](https://github.com/shenxn/libdyson/blob/7b19d1c96c151eb876d8d8fbb3a4d5f2917b86b3/libdyson/const.py#L4). For example, I have a TP04 which gave me a device type of 438. Therefore the correct device type in the dropdown would be "Pure Cool".

The workardound doesn't work on Home Assistant OS.
See [](https://github.com/shenxn/ha-dyson/issues/86#issuecomment-1008292130)

**Comment by albshin** [comment]
> > Dyson Cloud seems to use an older version of libdyson (0.8.7 vs 0.8.9) which [looks like it solves certificate related issues](https://github.com/shenxn/libdyson/releases/tag/v0.8.9). The package might just need a version bump. Also there needs to be a disclaimer about being logged out of the Dyson Link app. Authentication will fail if you're still logged in.
> > For anyone that wants to get your Dyson fan into HA, you can follow these steps as a workaround:
> > 
> > 1. Clone [libdyson](https://github.com/shenxn/libdyson)
> > 2. `cd` into the repository
> > 3. Run `pip install -r requirements.txt` (or `pip3` depending on your OS)
> > 4. **MAKE SURE YOU'RE LOGGED OUT OF THE DYSON LINK APP**
> > 5. Run `python get_devices.txt` (or `python3` depending on your OS) and complete the verification process
> > 6. Take the Serial, Credential, and Device Type and setup the Dyson Local integration. You can find out what your device type is by referencing [this](https://github.com/shenxn/libdyson/blob/7b19d1c96c151eb876d8d8fbb3a4d5f2917b86b3/libdyson/const.py#L4). For example, I have a TP04 which gave me a device type of 438. Therefore the correct device type in the dropdown would be "Pure Cool".
> 
> The workardound doesn't work on Home Assistant OS. See [#86 (comment)](https://github.com/shenxn/ha-dyson/issues/86#issuecomment-1008292130)

You can use my workaround to get your credentials on any device that has Python installed. You don't have to run it on your HA device.

**Comment by GitPetri** [comment]
> > > Dyson Cloud seems to use an older version of libdyson (0.8.7 vs 0.8.9) which [looks like it solves certificate related issues](https://github.com/shenxn/libdyson/releases/tag/v0.8.9). The package might just need a version bump. Also there needs to be a disclaimer about being logged out of the Dyson Link app. Authentication will fail if you're still logged in.
> > > For anyone that wants to get your Dyson fan into HA, you can follow these steps as a workaround:
> > > 
> > > 1. Clone [libdyson](https://github.com/shenxn/libdyson)
> > > 2. `cd` into the repository
> > > 3. Run `pip install -r requirements.txt` (or `pip3` depending on your OS)
> > > 4. **MAKE SURE YOU'RE LOGGED OUT OF THE DYSON LINK APP**
> > > 5. Run `python get_devices.txt` (or `python3` depending on your OS) and complete the verification process
> > > 6. Take the Serial, Credential, and Device Type and setup the Dyson Local integration. You can find out what your device type is by referencing [this](https://github.com/shenxn/libdyson/blob/7b19d1c96c151eb876d8d8fbb3a4d5f2917b86b3/libdyson/const.py#L4). For example, I have a TP04 which gave me a device type of 438. Therefore the correct device type in the dropdown would be "Pure Cool".
> > 
> > 
> > The workardound doesn't work on Home Assistant OS. See [#86 (comment)](https://github.com/shenxn/ha-dyson/issues/86#issuecomment-1008292130)
> 
> You can use my workaround to get your credentials on any device that has Python installed. You don't have to run it on your HA device.

Yes I have the credentials but the Dyson Cloud initialisation [doesn't work](https://github.com/shenxn/ha-dyson/issues/86#issue-1088374076)

**Comment by dhruvbhutani** [comment]
> Dyson Cloud seems to use an older version of libdyson (0.8.7 vs 0.8.9) which [looks like it solves certificate related issues](https://github.com/shenxn/libdyson/releases/tag/v0.8.9). The package might just need a version bump. Also there needs to be a disclaimer about being logged out of the Dyson Link app. Authentication will fail if you're still logged in.
> 
> For anyone that wants to get your Dyson fan into HA, you can follow these steps as a workaround:
> 
> 1. Clone [libdyson](https://github.com/shenxn/libdyson)
> 2. `cd` into the repository
> 3. Run `pip install -r requirements.txt` (or `pip3` depending on your OS)
> 4. **MAKE SURE YOU'RE LOGGED OUT OF THE DYSON LINK APP**
> 5. Run `python get_devices.txt` (or `python3` depending on your OS) and complete the verification process
> 6. Take the Serial, Credential, and Device Type and setup the Dyson Local integration. You can find out what your device type is by referencing [this](https://github.com/shenxn/libdyson/blob/7b19d1c96c151eb876d8d8fbb3a4d5f2917b86b3/libdyson/const.py#L4). For example, I have a TP04 which gave me a device type of 438. Therefore the correct device type in the dropdown would be "Pure Cool".

Getting this error. Think you might be able to help out? 

`Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: in
Email: email@email.com
Traceback (most recent call last):
  File "get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
  File "/Users/dhruv/Downloads/libdyson-main/libdyson/cloud/account.py", line 130, in login_email_otp
    account_status = response.json()["accountStatus"]
  File "/Users/dhruv/opt/anaconda3/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/dhruv/opt/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/dhruv/opt/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/dhruv/opt/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(base) Dhruvs-MacBook-Pro:libdyson-main dhruv$ 
`

**Comment by Kakise** [comment]
The problem should have been fixed in v0.16.4-3 according to my testing. Don't forget to logout of the app before attempting to connecting and use get_devices.py script in shenxn/libdyson if you still have troubles
