### ISSUE TITLE
PureCool Link Auto Mode and Pure Cool Link Air Quality both gone

### ISSUE THREAD

**Issue by Yop1403** [shenxn/ha-dyson#87]
Hi I've got a Dyson Pure Cool Link which has worked great with this integration.
Since a few revisions the:
(1) PureCool Link Auto Mode and the
(2) Pure Cool Link Air Quality
are both shown as not available anymore in the integration - refer to the 2 status remarks in red in the picture below - especially the PureCool Link Auto Mode is very important for the operation of the Pure Cool.

![Bildschirmfoto 2021-12-27 um 18 38 19 (2)](https://user-images.githubusercontent.com/7037677/147452977-eb5883b1-9542-48a4-8934-8f852e08a4d9.png)

![Bildschirmfoto 2021-12-27 um 18 40 22 (2)](https://user-images.githubusercontent.com/7037677/147453119-a4d6499f-d909-4710-9e9f-fe5b4aaa38c4.png)

**Comment by JakubMacoun** [comment]
I have the same issue and I actually removed those entites as I thought it is just solved another way.
Only later I realized that my purifier turns always with speed 4 instead of auto on _fan.turn_on_ and I don't see any option how to turn it on in auto mode. Please think of re-adding those deleted entities while fixing this (if the entities are supposed to be there). Thank you.

**Comment by homekitter** [comment]
Change seems to have come from https://github.com/shenxn/ha-dyson/pull/69

**Comment by homekitter** [comment]
Further discussion here it seems https://github.com/shenxn/ha-dyson/issues/75#issuecomment-991919715

**Comment by Kakise** [comment]
Closed as these changes were intended to make this extension more compliant with HA best practices

**Comment by CumpsD** [comment]
Is the air quality still available somewhere, after following these best practices?

**Comment by CumpsD** [comment]
> Is the air quality still available somewhere, after following these best practices?

Nevermind, I figured out they are now sensors:

![image](https://user-images.githubusercontent.com/1201644/188449624-562b8164-e36d-459c-bea3-edbd4936d274.png)

But which one used to be "air quality" ;)
