### ISSUE TITLE
Unable to see sensors in "statistics" graph

### ISSUE THREAD

**Issue by shadyabhi** [shenxn/ha-dyson#89]
HASS docs say, when sensors are being sent, they should have the right property set: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

![image](https://user-images.githubusercontent.com/631797/148706045-4c84e3dd-0f49-4ed7-8e2a-1b6dd618a8d4.png)

I know that my integration works because I'm able to see the sensors being populated on the "History" page

![image](https://user-images.githubusercontent.com/631797/148706120-74ae15c7-9743-461c-b7f7-2358eb5458f3.png)

**Comment by Kakise** [comment]
The state_class is now set to "Measurement" for the sensors. They are able to be added to a stat graph with no issue now. :)
