### ISSUE TITLE
Some services missing

### ISSUE THREAD

**Issue by jerryzou** [shenxn/ha-dyson#9]
I've tried the dyson_local today and it's working really well.

Thank shenxn for coming up with such a fantastic solution for running dyson devices completely off the cloud.

I just noticed compared with the official dyson integration, some services are missing. like
- dyson.set_flow_direction_front
- dyson.set_timer
- ...

It would be great to have these servcies integrated... :)

**Comment by shenxn** [comment]
Yes, I'll add those soon.

**Comment by jerryzou** [comment]
Thank you so much!

**Comment by shenxn** [comment]
Also, note that to set night mode, continuous monitoring, and front air flow, there are switches exposed instead of custom services. You can use `switch.turn_on` and `switch.turn_off` on those switch entities in scripts and automation.

**Comment by jerryzou** [comment]
That's true. I should have noticed them... Thanks again!

**Comment by shenxn** [comment]
Additional services added in version 0.5.2

**Comment by jerryzou** [comment]
Noted and thanks!
