### ISSUE TITLE
dyson pure hot & cold VOC in HA does not match official app

### ISSUE THREAD

**Issue by drizuid** [shenxn/ha-dyson#92]
Hello team, thanks for all you do. I just wanted to share what i've been seeing as of late.

Basically, this integration in HA has never showed below a 3. However, generally speaking, VOC shows as a 0 in the official app. I thought perhaps this is related to measurement method, but to be honest, I did not dig in.

![officialapp](https://user-images.githubusercontent.com/40674481/149851990-ac4445cb-6b40-44c0-920c-b8b3c4c9f1ff.png)
<img width="367" alt="ha card" src="https://user-images.githubusercontent.com/40674481/149852006-553bb6d3-6972-4213-a10e-bb86b39ca15c.png">
the above were taken at the same time, you'll notice HA reflects a 4 (this is in the "fair" state) while the official app reflects a 0 (good state). 
I checked the history and saw it's not been below a 3 in any meaningful time.
<img width="1714" alt="voc history" src="https://user-images.githubusercontent.com/40674481/149852068-b88e9369-5c4d-4f07-9b25-42c538a01492.png">

logs: https://0bin.net/paste/2Bbje5jA#cfIGkZBIeHcs-jLdjzr9U9zgioV90u5+zTzL8yeSh0P

the only thing i really noticed, and this may be purely cosmetic is in the official app, pm2.5 and pm10 are measured in micrograms per cubic meter, but in the HA integration, VOC is also using this measurement, so perhaps it's a conversion thing? (the same is true for NO2, but i dont see issues with this one) 

Anyway, I hope this is useful information, please let me know if I can provide any other details.

**Comment by Kakise** [comment]
Honestly I can't reproduce, I tried different things to simulate this but the only conclusion I came to is that the Dyson app doesn't use the same readings sent by MQTT. Which is not a problem for anyone else. I'll reopen it and come back to it if someone else has the same issue
