### ISSUE TITLE
Add support for Pure Hot+Cool Formaldehyde ?

### ISSUE THREAD

**Issue by lolongan** [shenxn/ha-dyson#95]
All is in the title. 
Is it possible to add support for the Pure Hot+Cool Formaldehyde ?
When adding new device in Dyson Local, I see the "Pure Cool Formaldehyde" but no "Pure Hot+Cool Formaldehyde".
I've tried with "Pure Cool Formaldehyde" and "Pure Hot+Cool", "Pure Hot+Cool (New)", "Pure Hot+Cool Link" but none of them works, always get an error "Failed to connect".
Note that I have also a Pure Hot+Cool and it works with the integration, so assume that the issue is the non support of the considered device type

**Comment by Kakise** [comment]
I do not have the device with me so I can't really do that. Pull requests are encouraged :S Right now I am focusing all of my spare time into making the integration official.
