### ISSUE TITLE
H+C Link not connecting

### ISSUE THREAD

**Issue by weesteev** [shenxn/ha-dyson#97]
Integration installs ok, config.yaml updated and tried both options to connect my device (type 455). Get a "failed to connect" error. Any ideas? I've starred out the ID below after it failed to connect just to show the format I'm using. Its the same error if i use the host address as well (192.168.1.25).

<img width="448" alt="Screenshot 2022-01-27 200050" src="https://user-images.githubusercontent.com/76874416/151434666-5757fe13-67ed-4562-ba80-0ef90cda8671.png">

**Comment by Kakise** [comment]
With what I'm seeing I can figure that you did not write the full SSID ? (at least I think so). You need to enter the full SSID with the DYSON- part and the -455 that is written in the sticker, and it should work fine ! :)
